// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

var os_File_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("os.File", runtime.StructOwnershipHostOpaque, "struct {}")

var os_FileInfo_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("os.FileInfo", runtime.StructOwnershipVMValue, "struct { Name String; Size Int64; }")

var os_Nested_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("os.Nested", runtime.StructOwnershipVMValue, "struct { Info os.FileInfo; Level Int64; }")

var native_NativeStruct_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("native.NativeStruct", runtime.StructOwnershipVMValue, "struct { Msg String; Value Int64; }")

var native_NativeHandle_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("native.NativeHandle", runtime.StructOwnershipHostOpaque, "struct {}")

var Selector_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("Selector", runtime.StructOwnershipHostOpaque, "struct {}")

var Page_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("Page", runtime.StructOwnershipHostOpaque, "struct { GetByPlaceholder function(HostRef<Page>, String, ...Bool) HostRef<Selector>; }")

const (
	MethodID_MockOS_Open  = 1
	MethodID_MockOS_Name  = 2
	MethodID_MockOS_Stat  = 3
	MethodID_MockOS_Read  = 4
	MethodID_MockOS_Write = 5
	MethodID_MockOS_Close = 6
	MethodID_MockOS_Deep  = 7
)

type MockOSProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewMockOSProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) MockOS {
	return &MockOSProxy{bridge: bridge, registry: registry}
}

func (__p *MockOSProxy) Open(name string) (*File, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(name))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Open, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 *File
	// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.GetTyped(id, "os.File"); ok {
				v_0 = obj.(*File)
			}
		}
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *MockOSProxy) Name(f *File) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	// HostRef<T> crosses the FFI boundary as an opaque handle ID.
	if f == nil {
		wireBuf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			wireBuf.WriteUvarint(uint64(__p.registry.RegisterTyped(f, "os.File")))
		} else {
			wireBuf.WriteUvarint(0)
		}
	}

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Name, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *MockOSProxy) Stat(f *File) (FileInfo, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	// HostRef<T> crosses the FFI boundary as an opaque handle ID.
	if f == nil {
		wireBuf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			wireBuf.WriteUvarint(uint64(__p.registry.RegisterTyped(f, "os.File")))
		} else {
			wireBuf.WriteUvarint(0)
		}
	}

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Stat, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return FileInfo{}, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 FileInfo
	v_0.Name = string(retBuf.ReadString())
	{
		tmp := retBuf.ReadVarint()
		v_0.Size = int64(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *MockOSProxy) Read(f *File, b []byte) (int64, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	// HostRef<T> crosses the FFI boundary as an opaque handle ID.
	if f == nil {
		wireBuf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			wireBuf.WriteUvarint(uint64(__p.registry.RegisterTyped(f, "os.File")))
		} else {
			wireBuf.WriteUvarint(0)
		}
	}
	wireBuf.WriteBytes(b)

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Read, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *MockOSProxy) Write(f *File, b []byte) (int64, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	// HostRef<T> crosses the FFI boundary as an opaque handle ID.
	if f == nil {
		wireBuf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			wireBuf.WriteUvarint(uint64(__p.registry.RegisterTyped(f, "os.File")))
		} else {
			wireBuf.WriteUvarint(0)
		}
	}
	wireBuf.WriteBytes(b)

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Write, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *MockOSProxy) Close(f *File) error {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	// HostRef<T> crosses the FFI boundary as an opaque handle ID.
	if f == nil {
		wireBuf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			wireBuf.WriteUvarint(uint64(__p.registry.RegisterTyped(f, "os.File")))
		} else {
			wireBuf.WriteUvarint(0)
		}
	}

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Close, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return err
	}
	retBuf := ffigo.NewReader(retData)
	var err_0 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_0 = obj.(error)
				} else {
					err_0 = ed
				}
			} else {
				err_0 = ed
			}
		}
	}
	return err_0
}

func (__p *MockOSProxy) Deep(n Nested) Nested {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(n.Info.Name))
	wireBuf.WriteVarint(int64(n.Info.Size))
	wireBuf.WriteVarint(int64(n.Level))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_MockOS_Deep, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 Nested
	v_0.Info.Name = string(retBuf.ReadString())
	{
		tmp := retBuf.ReadVarint()
		v_0.Info.Size = int64(tmp)
	}
	{
		tmp := retBuf.ReadVarint()
		v_0.Level = int64(tmp)
	}
	return v_0
}

func MockOSHostRouter(ctx context.Context, impl MockOS, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Open":
			methodID = MethodID_MockOS_Open
		case "Name":
			methodID = MethodID_MockOS_Name
		case "Stat":
			methodID = MethodID_MockOS_Stat
		case "Read":
			methodID = MethodID_MockOS_Read
		case "Write":
			methodID = MethodID_MockOS_Write
		case "Close":
			methodID = MethodID_MockOS_Close
		case "Deep":
			methodID = MethodID_MockOS_Deep
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_MockOS_Open:
		var name string
		name = string(reqBuf.ReadString())
		r0, err := impl.Open(name)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "os.File")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_MockOS_Name:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		r0 := impl.Name(f)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_MockOS_Stat:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		r0, err := impl.Stat(f)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0.Name))
		resBuf.WriteVarint(int64(r0.Size))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_MockOS_Read:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Read(f, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_MockOS_Write:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Write(f, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_MockOS_Close:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		err := impl.Close(f)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_MockOS_Deep:
		var n Nested
		n.Info.Name = string(reqBuf.ReadString())
		{
			tmp := reqBuf.ReadVarint()
			n.Info.Size = int64(tmp)
		}
		{
			tmp := reqBuf.ReadVarint()
			n.Level = int64(tmp)
		}
		r0 := impl.Deep(n)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0.Info.Name))
		resBuf.WriteVarint(int64(r0.Info.Size))
		resBuf.WriteVarint(int64(r0.Level))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var MockOS_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Open", 1, runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(HostRef<os.File>, Error)", runtime.FFIParamIn), ""},
	{"Name", 2, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>) String", runtime.FFIParamIn), ""},
	{"Stat", 3, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>) tuple(os.FileInfo, Error)", runtime.FFIParamIn), ""},
	{"Read", 4, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>, TypeBytes) tuple(Int64, Error)", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Write", 5, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>, TypeBytes) tuple(Int64, Error)", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Close", 6, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>) Error", runtime.FFIParamIn), ""},
	{"Deep", 7, runtime.MustParseRuntimeFuncSigWithModes("function(os.Nested) os.Nested", runtime.FFIParamIn), ""},
}

type MockOS_Bridge struct {
	Impl     MockOS
	Registry *ffigo.HandleRegistry
}

func (b *MockOS_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return MockOSHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *MockOS_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return MockOSHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *MockOS_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterMockOS(executor interface{ RegisterConstant(string, string) }, impl MockOS, registry *ffigo.HandleRegistry) {
	bridge := &MockOS_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("os.Open", bridge, MockOS_FFI_Schemas[0].MethodID, MockOS_FFI_Schemas[0].Sig, MockOS_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("os.Name", bridge, MockOS_FFI_Schemas[1].MethodID, MockOS_FFI_Schemas[1].Sig, MockOS_FFI_Schemas[1].Doc)
	registrar.RegisterFFISchema("os.Stat", bridge, MockOS_FFI_Schemas[2].MethodID, MockOS_FFI_Schemas[2].Sig, MockOS_FFI_Schemas[2].Doc)
	registrar.RegisterFFISchema("os.Read", bridge, MockOS_FFI_Schemas[3].MethodID, MockOS_FFI_Schemas[3].Sig, MockOS_FFI_Schemas[3].Doc)
	registrar.RegisterFFISchema("os.Write", bridge, MockOS_FFI_Schemas[4].MethodID, MockOS_FFI_Schemas[4].Sig, MockOS_FFI_Schemas[4].Doc)
	registrar.RegisterFFISchema("os.Close", bridge, MockOS_FFI_Schemas[5].MethodID, MockOS_FFI_Schemas[5].Sig, MockOS_FFI_Schemas[5].Doc)
	registrar.RegisterFFISchema("os.Deep", bridge, MockOS_FFI_Schemas[6].MethodID, MockOS_FFI_Schemas[6].Sig, MockOS_FFI_Schemas[6].Doc)
	registerStructSchema("os.File", os_File_FFI_StructSchema)
	registerStructSchema("os.FileInfo", os_FileInfo_FFI_StructSchema)
	registerStructSchema("os.Nested", os_Nested_FFI_StructSchema)
}

const (
	MethodID_ContextMock_WithContext    = 1
	MethodID_ContextMock_WithoutContext = 2
)

type ContextMockProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewContextMockProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) ContextMock {
	return &ContextMockProxy{bridge: bridge, registry: registry}
}

func (__p *ContextMockProxy) WithContext(ctx context.Context, key string) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(key))

	__ret, err := __p.bridge.Call(ctx, &ffigo.FFICallRequest{MethodID: MethodID_ContextMock_WithContext, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *ContextMockProxy) WithoutContext(val string) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(val))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_ContextMock_WithoutContext, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func ContextMockHostRouter(ctx context.Context, impl ContextMock, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "WithContext":
			methodID = MethodID_ContextMock_WithContext
		case "WithoutContext":
			methodID = MethodID_ContextMock_WithoutContext
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_ContextMock_WithContext:
		var key string
		key = string(reqBuf.ReadString())
		r0 := impl.WithContext(ctx, key)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_ContextMock_WithoutContext:
		var val string
		val = string(reqBuf.ReadString())
		r0 := impl.WithoutContext(val)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var ContextMock_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"WithContext", 1, runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), ""},
	{"WithoutContext", 2, runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), ""},
}

type ContextMock_Bridge struct {
	Impl     ContextMock
	Registry *ffigo.HandleRegistry
}

func (b *ContextMock_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ContextMockHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *ContextMock_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ContextMockHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *ContextMock_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterContextMock(executor interface{ RegisterConstant(string, string) }, impl ContextMock, registry *ffigo.HandleRegistry) {
	bridge := &ContextMock_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registrar.RegisterFFISchema("ctx_test.WithContext", bridge, ContextMock_FFI_Schemas[0].MethodID, ContextMock_FFI_Schemas[0].Sig, ContextMock_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("ctx_test.WithoutContext", bridge, ContextMock_FFI_Schemas[1].MethodID, ContextMock_FFI_Schemas[1].Sig, ContextMock_FFI_Schemas[1].Doc)
}

const (
	MethodID_NativeMock_GetStruct = 1
	MethodID_NativeMock_GetPtr    = 2
	MethodID_NativeMock_SetStruct = 3
	MethodID_NativeMock_SetPtr    = 4
)

type NativeMockProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewNativeMockProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) NativeMock {
	return &NativeMockProxy{bridge: bridge, registry: registry}
}

func (__p *NativeMockProxy) GetStruct() NativeStruct {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_NativeMock_GetStruct, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 NativeStruct
	v_0.Msg = string(retBuf.ReadString())
	{
		tmp := retBuf.ReadVarint()
		v_0.Value = int64(tmp)
	}
	return v_0
}

func (__p *NativeMockProxy) GetPtr() *NativeHandle {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_NativeMock_GetPtr, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 *NativeHandle
	// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.GetTyped(id, "native.NativeHandle"); ok {
				v_0 = obj.(*NativeHandle)
			}
		}
	}
	return v_0
}

func (__p *NativeMockProxy) SetStruct(s NativeStruct) int64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(s.Msg))
	wireBuf.WriteVarint(int64(s.Value))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_NativeMock_SetStruct, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	return v_0
}

func (__p *NativeMockProxy) SetPtr(s *NativeHandle) int64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	// HostRef<T> crosses the FFI boundary as an opaque handle ID.
	if s == nil {
		wireBuf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			wireBuf.WriteUvarint(uint64(__p.registry.RegisterTyped(s, "native.NativeHandle")))
		} else {
			wireBuf.WriteUvarint(0)
		}
	}

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_NativeMock_SetPtr, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	return v_0
}

func NativeMockHostRouter(ctx context.Context, impl NativeMock, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "GetStruct":
			methodID = MethodID_NativeMock_GetStruct
		case "GetPtr":
			methodID = MethodID_NativeMock_GetPtr
		case "SetStruct":
			methodID = MethodID_NativeMock_SetStruct
		case "SetPtr":
			methodID = MethodID_NativeMock_SetPtr
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_NativeMock_GetStruct:
		r0 := impl.GetStruct()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0.Msg))
		resBuf.WriteVarint(int64(r0.Value))
		return resBuf.Bytes(), nil
	case MethodID_NativeMock_GetPtr:
		r0 := impl.GetPtr()
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "native.NativeHandle")))
		}
		return resBuf.Bytes(), nil
	case MethodID_NativeMock_SetStruct:
		var s NativeStruct
		s.Msg = string(reqBuf.ReadString())
		{
			tmp := reqBuf.ReadVarint()
			s.Value = int64(tmp)
		}
		r0 := impl.SetStruct(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case MethodID_NativeMock_SetPtr:
		var s *NativeHandle
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "native.NativeHandle"); err == nil {
				s = obj.(*NativeHandle)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "s", err)
			}
		}
		r0 := impl.SetPtr(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var NativeMock_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"GetStruct", 1, runtime.MustParseRuntimeFuncSig("function() native.NativeStruct"), ""},
	{"GetPtr", 2, runtime.MustParseRuntimeFuncSig("function() HostRef<native.NativeHandle>"), ""},
	{"SetStruct", 3, runtime.MustParseRuntimeFuncSigWithModes("function(native.NativeStruct) Int64", runtime.FFIParamIn), ""},
	{"SetPtr", 4, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<native.NativeHandle>) Int64", runtime.FFIParamIn), ""},
}

type NativeMock_Bridge struct {
	Impl     NativeMock
	Registry *ffigo.HandleRegistry
}

func (b *NativeMock_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return NativeMockHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *NativeMock_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return NativeMockHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *NativeMock_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterNativeMock(executor interface{ RegisterConstant(string, string) }, impl NativeMock, registry *ffigo.HandleRegistry) {
	bridge := &NativeMock_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("native.GetStruct", bridge, NativeMock_FFI_Schemas[0].MethodID, NativeMock_FFI_Schemas[0].Sig, NativeMock_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("native.GetPtr", bridge, NativeMock_FFI_Schemas[1].MethodID, NativeMock_FFI_Schemas[1].Sig, NativeMock_FFI_Schemas[1].Doc)
	registrar.RegisterFFISchema("native.SetStruct", bridge, NativeMock_FFI_Schemas[2].MethodID, NativeMock_FFI_Schemas[2].Sig, NativeMock_FFI_Schemas[2].Doc)
	registrar.RegisterFFISchema("native.SetPtr", bridge, NativeMock_FFI_Schemas[3].MethodID, NativeMock_FFI_Schemas[3].Sig, NativeMock_FFI_Schemas[3].Doc)
	registerStructSchema("native.NativeStruct", native_NativeStruct_FFI_StructSchema)
	registerStructSchema("native.NativeHandle", native_NativeHandle_FFI_StructSchema)
}

const (
	MethodID_Page_GetByPlaceholder = 1
)

func PageHostRouter(ctx context.Context, impl *Page, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "GetByPlaceholder":
			methodID = MethodID_Page_GetByPlaceholder
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Page_GetByPlaceholder:
		var __recv *Page
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "Page"); err == nil {
				__recv = obj.(*Page)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var text string
		text = string(reqBuf.ReadString())
		var exact []bool
		l_exact := int(reqBuf.ReadUvarint())
		exact = make([]bool, l_exact)
		for i_exact := 0; i_exact < l_exact; i_exact++ {
			exact[i_exact] = bool(reqBuf.ReadBool())
		}
		r0 := __recv.GetByPlaceholder(text, exact...)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "Selector")))
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Page_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"GetByPlaceholder", 1, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<Page>, String, ...Bool) HostRef<Selector>", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
}

type Page_Bridge struct {
	Impl     *Page
	Registry *ffigo.HandleRegistry
}

func (b *Page_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return PageHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Page_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return PageHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Page_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterPage(executor interface{ RegisterConstant(string, string) }, registry *ffigo.HandleRegistry) {
	bridge := &Page_Bridge{Impl: nil, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("Page.GetByPlaceholder", bridge, Page_FFI_Schemas[0].MethodID, Page_FFI_Schemas[0].Sig, Page_FFI_Schemas[0].Doc)
	registerStructSchema("Selector", Selector_FFI_StructSchema)
	registerStructSchema("Page", Page_FFI_StructSchema)
}
