// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

var os_File_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("os.File", runtime.StructOwnershipHostOpaque, "struct {}")

var os_FileInfo_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("os.FileInfo", runtime.StructOwnershipVMValue, "struct { Name String; Size Int64; }")

var os_Nested_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("os.Nested", runtime.StructOwnershipVMValue, "struct { Info os.FileInfo; Level Int64; }")

var native_NativeStruct_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("native.NativeStruct", runtime.StructOwnershipVMValue, "struct { Msg String; Value Int64; }")

var native_NativeHandle_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("native.NativeHandle", runtime.StructOwnershipHostOpaque, "struct {}")

var Selector_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("Selector", runtime.StructOwnershipHostOpaque, "struct {}")

var Page_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("Page", runtime.StructOwnershipHostOpaque, "struct { GetByPlaceholder function(HostRef<Page>, String, ...Bool) HostRef<Selector>; }")

const (
	methodIDMockOSOpen  = 1
	methodIDMockOSName  = 2
	methodIDMockOSStat  = 3
	methodIDMockOSRead  = 4
	methodIDMockOSWrite = 5
	methodIDMockOSClose = 6
	methodIDMockOSDeep  = 7
)

func mockOSHostRouter(ctx context.Context, impl MockOS, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Open":
			methodID = methodIDMockOSOpen
		case "Name":
			methodID = methodIDMockOSName
		case "Stat":
			methodID = methodIDMockOSStat
		case "Read":
			methodID = methodIDMockOSRead
		case "Write":
			methodID = methodIDMockOSWrite
		case "Close":
			methodID = methodIDMockOSClose
		case "Deep":
			methodID = methodIDMockOSDeep
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDMockOSOpen:
		var name string
		name = string(reqBuf.ReadString())
		r0, err := impl.Open(name)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "os.File")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMockOSName:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		r0 := impl.Name(f)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDMockOSStat:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		r0, err := impl.Stat(f)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0.Name))
		resBuf.WriteVarint(int64(r0.Size))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMockOSRead:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Read(f, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMockOSWrite:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Write(f, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMockOSClose:
		var f *File
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "os.File"); err == nil {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "f", err)
			}
		}
		err := impl.Close(f)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMockOSDeep:
		var n Nested
		n.Info.Name = string(reqBuf.ReadString())
		{
			tmp := reqBuf.ReadVarint()
			n.Info.Size = int64(tmp)
		}
		{
			tmp := reqBuf.ReadVarint()
			n.Level = int64(tmp)
		}
		r0 := impl.Deep(n)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0.Info.Name))
		resBuf.WriteVarint(int64(r0.Info.Size))
		resBuf.WriteVarint(int64(r0.Level))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var mockOSRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "os", MemberName: "Open", RouteName: "os.Open", MethodID: methodIDMockOSOpen, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(HostRef<os.File>, Error)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "os", MemberName: "Name", RouteName: "os.Name", MethodID: methodIDMockOSName, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>) String", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "os", MemberName: "Stat", RouteName: "os.Stat", MethodID: methodIDMockOSStat, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>) tuple(os.FileInfo, Error)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "os", MemberName: "Read", RouteName: "os.Read", MethodID: methodIDMockOSRead, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>, TypeBytes) tuple(Int64, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "os", MemberName: "Write", RouteName: "os.Write", MethodID: methodIDMockOSWrite, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>, TypeBytes) tuple(Int64, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "os", MemberName: "Close", RouteName: "os.Close", MethodID: methodIDMockOSClose, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<os.File>) Error", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "os", MemberName: "Deep", RouteName: "os.Deep", MethodID: methodIDMockOSDeep, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(os.Nested) os.Nested", runtime.FFIParamIn), Doc: ""},
}

func SurfaceMockOS(impl MockOS) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(mockOSRoutes)
	schema.AddStruct("os.File", os_File_FFI_StructSchema)
	schema.AddStruct("os.FileInfo", os_FileInfo_FFI_StructSchema)
	schema.AddStruct("os.Nested", os_Nested_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return mockOSHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}

const (
	methodIDContextMockWithContext    = 1
	methodIDContextMockWithoutContext = 2
)

func contextMockHostRouter(ctx context.Context, impl ContextMock, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "WithContext":
			methodID = methodIDContextMockWithContext
		case "WithoutContext":
			methodID = methodIDContextMockWithoutContext
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDContextMockWithContext:
		var key string
		key = string(reqBuf.ReadString())
		r0 := impl.WithContext(ctx, key)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDContextMockWithoutContext:
		var val string
		val = string(reqBuf.ReadString())
		r0 := impl.WithoutContext(val)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var contextMockRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "ctx_test", MemberName: "WithContext", RouteName: "ctx_test.WithContext", MethodID: methodIDContextMockWithContext, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "ctx_test", MemberName: "WithoutContext", RouteName: "ctx_test.WithoutContext", MethodID: methodIDContextMockWithoutContext, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), Doc: ""},
}

func SurfaceContextMock(impl ContextMock) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(contextMockRoutes)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return contextMockHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}

const (
	methodIDNativeMockGetStruct = 1
	methodIDNativeMockGetPtr    = 2
	methodIDNativeMockSetStruct = 3
	methodIDNativeMockSetPtr    = 4
)

func nativeMockHostRouter(ctx context.Context, impl NativeMock, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "GetStruct":
			methodID = methodIDNativeMockGetStruct
		case "GetPtr":
			methodID = methodIDNativeMockGetPtr
		case "SetStruct":
			methodID = methodIDNativeMockSetStruct
		case "SetPtr":
			methodID = methodIDNativeMockSetPtr
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDNativeMockGetStruct:
		r0 := impl.GetStruct()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0.Msg))
		resBuf.WriteVarint(int64(r0.Value))
		return resBuf.Bytes(), nil
	case methodIDNativeMockGetPtr:
		r0 := impl.GetPtr()
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "native.NativeHandle")))
		}
		return resBuf.Bytes(), nil
	case methodIDNativeMockSetStruct:
		var s NativeStruct
		s.Msg = string(reqBuf.ReadString())
		{
			tmp := reqBuf.ReadVarint()
			s.Value = int64(tmp)
		}
		r0 := impl.SetStruct(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDNativeMockSetPtr:
		var s *NativeHandle
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "native.NativeHandle"); err == nil {
				s = obj.(*NativeHandle)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "s", err)
			}
		}
		r0 := impl.SetPtr(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var nativeMockRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "native", MemberName: "GetStruct", RouteName: "native.GetStruct", MethodID: methodIDNativeMockGetStruct, Sig: runtime.MustParseRuntimeFuncSig("function() native.NativeStruct"), Doc: ""},
	{PackagePath: "native", MemberName: "GetPtr", RouteName: "native.GetPtr", MethodID: methodIDNativeMockGetPtr, Sig: runtime.MustParseRuntimeFuncSig("function() HostRef<native.NativeHandle>"), Doc: ""},
	{PackagePath: "native", MemberName: "SetStruct", RouteName: "native.SetStruct", MethodID: methodIDNativeMockSetStruct, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(native.NativeStruct) Int64", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "native", MemberName: "SetPtr", RouteName: "native.SetPtr", MethodID: methodIDNativeMockSetPtr, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<native.NativeHandle>) Int64", runtime.FFIParamIn), Doc: ""},
}

func SurfaceNativeMock(impl NativeMock) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(nativeMockRoutes)
	schema.AddStruct("native.NativeStruct", native_NativeStruct_FFI_StructSchema)
	schema.AddStruct("native.NativeHandle", native_NativeHandle_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return nativeMockHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}

const (
	methodIDPageGetByPlaceholder = 1
)

func pageHostRouter(ctx context.Context, impl *Page, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "GetByPlaceholder":
			methodID = methodIDPageGetByPlaceholder
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDPageGetByPlaceholder:
		var __recv *Page
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "Page"); err == nil {
				__recv = obj.(*Page)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var text string
		text = string(reqBuf.ReadString())
		var exact []bool
		l_exact := int(reqBuf.ReadUvarint())
		exact = make([]bool, l_exact)
		for i_exact := 0; i_exact < l_exact; i_exact++ {
			exact[i_exact] = bool(reqBuf.ReadBool())
		}
		r0 := __recv.GetByPlaceholder(text, exact...)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "Selector")))
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var pageRoutes = []runtime.FFIRouteDecl{
	{TypeName: "Page", MethodName: "GetByPlaceholder", RouteName: "Page.GetByPlaceholder", MethodID: methodIDPageGetByPlaceholder, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<Page>, String, ...Bool) HostRef<Selector>", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
}

func SurfacePage() *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(pageRoutes)
	schema.AddStruct("Selector", Selector_FFI_StructSchema)
	schema.AddStruct("Page", Page_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return pageHostRouter(callCtx, nil, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
