// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDMapTestEchoMap    = 1
	methodIDMapTestGetMap     = 2
	methodIDMapTestProcessMap = 3
	methodIDMapTestEchoIntMap = 4
)

func mapTestHostRouter(ctx context.Context, impl MapTest, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "EchoMap":
			methodID = methodIDMapTestEchoMap
		case "GetMap":
			methodID = methodIDMapTestGetMap
		case "ProcessMap":
			methodID = methodIDMapTestProcessMap
		case "EchoIntMap":
			methodID = methodIDMapTestEchoIntMap
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDMapTestEchoMap:
		var m map[string]string
		l_m, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "map")
		m = make(map[string]string)
		for i_m := 0; i_m < l_m; i_m++ {
			var k string
			var v string
			{
				tmp, _ := reqBuf.ReadString()
				k = string(tmp)
			}
			{
				tmp, _ := reqBuf.ReadString()
				v = string(tmp)
			}
			m[k] = v
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for MapTest.EchoMap failed: %w", err)
		}
		r0, err := impl.EchoMap(ctx, m)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for k, v := range r0 {
			resBuf.WriteString(string(k))
			resBuf.WriteString(string(v))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMapTestGetMap:
		r0, err := impl.GetMap(ctx)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for k, v := range r0 {
			resBuf.WriteString(string(k))
			resBuf.WriteVarint(int64(v))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMapTestProcessMap:
		var m map[string]int64
		l_m, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "map")
		m = make(map[string]int64)
		for i_m := 0; i_m < l_m; i_m++ {
			var k string
			var v int64
			{
				tmp, _ := reqBuf.ReadString()
				k = string(tmp)
			}
			{
				tmp, _ := reqBuf.ReadVarint()
				v = int64(tmp)
			}
			m[k] = v
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for MapTest.ProcessMap failed: %w", err)
		}
		r0, err := impl.ProcessMap(ctx, m)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDMapTestEchoIntMap:
		var m map[int64]string
		l_m, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "map")
		m = make(map[int64]string)
		for i_m := 0; i_m < l_m; i_m++ {
			var k int64
			var v string
			{
				tmp, _ := reqBuf.ReadVarint()
				k = int64(tmp)
			}
			{
				tmp, _ := reqBuf.ReadString()
				v = string(tmp)
			}
			m[k] = v
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for MapTest.EchoIntMap failed: %w", err)
		}
		r0, err := impl.EchoIntMap(ctx, m)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for k, v := range r0 {
			resBuf.WriteVarint(int64(k))
			resBuf.WriteString(string(v))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var mapTestRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "ffigen_test", MemberName: "EchoMap", RouteName: "ffigen_test.EchoMap", MethodID: methodIDMapTestEchoMap, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Map<String, String>) tuple(Map<String, String>, Error)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "ffigen_test", MemberName: "GetMap", RouteName: "ffigen_test.GetMap", MethodID: methodIDMapTestGetMap, Sig: runtime.MustParseRuntimeFuncSig("function() tuple(Map<String, Int64>, Error)"), Doc: ""},
	{PackagePath: "ffigen_test", MemberName: "ProcessMap", RouteName: "ffigen_test.ProcessMap", MethodID: methodIDMapTestProcessMap, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Map<String, Int64>) tuple(Int64, Error)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "ffigen_test", MemberName: "EchoIntMap", RouteName: "ffigen_test.EchoIntMap", MethodID: methodIDMapTestEchoIntMap, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Map<Int64, String>) tuple(Map<Int64, String>, Error)", runtime.FFIParamIn), Doc: ""},
}

func SurfaceMapTest(impl MapTest) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	if err := schema.AddRouteDecls(mapTestRoutes); err != nil {
		panic(err)
	}
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return mapTestHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
