// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

var Rect_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("Rect", runtime.StructOwnershipVMValue, "struct { A Point; B Point; }")

var Point_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("Point", runtime.StructOwnershipVMValue, "struct { X Int64; Y Int64; }")

const (
	methodIDMockShapeAPIGetRect = 1
	methodIDMockShapeAPIArea    = 2
)

func mockShapeAPIHostRouter(ctx context.Context, impl MockShapeAPI, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "GetRect":
			methodID = methodIDMockShapeAPIGetRect
		case "Area":
			methodID = methodIDMockShapeAPIArea
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDMockShapeAPIGetRect:
		r0 := impl.GetRect()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0.A.X))
		resBuf.WriteVarint(int64(r0.A.Y))
		resBuf.WriteVarint(int64(r0.B.X))
		resBuf.WriteVarint(int64(r0.B.Y))
		return resBuf.Bytes(), nil
	case methodIDMockShapeAPIArea:
		var r Rect
		{
			tmp, _ := reqBuf.ReadVarint()
			r.A.X = int64(tmp)
		}
		{
			tmp, _ := reqBuf.ReadVarint()
			r.A.Y = int64(tmp)
		}
		{
			tmp, _ := reqBuf.ReadVarint()
			r.B.X = int64(tmp)
		}
		{
			tmp, _ := reqBuf.ReadVarint()
			r.B.Y = int64(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for MockShapeAPI.Area failed: %w", err)
		}
		r0 := impl.Area(r)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var mockShapeAPIRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "", MemberName: "GetRect", RouteName: ".GetRect", MethodID: methodIDMockShapeAPIGetRect, Sig: runtime.MustParseRuntimeFuncSig("function() Rect"), Doc: ""},
	{PackagePath: "", MemberName: "Area", RouteName: ".Area", MethodID: methodIDMockShapeAPIArea, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Rect) Int64", runtime.FFIParamIn), Doc: ""},
}

func SurfaceMockShapeAPILibrary(prefix string, impl MockShapeAPI) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	routes := make([]runtime.FFIRouteDecl, 0, len(mockShapeAPIRoutes))
	for _, route := range mockShapeAPIRoutes {
		route.PackagePath = prefix
		route.RouteName = prefix + "." + route.MemberName
		routes = append(routes, route)
	}
	schema.AddRouteDecls(routes)
	schema.AddStruct("Rect", Rect_FFI_StructSchema)
	schema.AddStruct("Point", Point_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return mockShapeAPIHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
