// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDLoggerLog      = 1
	methodIDLoggerInternal = 2
)

func loggerHostRouter(ctx context.Context, impl Logger, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Log":
			methodID = methodIDLoggerLog
		case "Internal":
			methodID = methodIDLoggerInternal
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDLoggerLog:
		var msg string
		msg = string(reqBuf.ReadString())
		var level string
		level = string(reqBuf.ReadString())
		var code int64
		{
			tmp := reqBuf.ReadVarint()
			code = int64(tmp)
		}
		impl.Log(ctx, msg, level, code)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case methodIDLoggerInternal:
		var arg0 string
		arg0 = string(reqBuf.ReadString())
		var arg1 string
		arg1 = string(reqBuf.ReadString())
		var arg2 int64
		{
			tmp := reqBuf.ReadVarint()
			arg2 = int64(tmp)
		}
		impl.Internal(arg0, arg1, arg2)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var loggerRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "logger", MemberName: "Log", RouteName: "logger.Log", MethodID: methodIDLoggerLog, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, Int64) Void", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "logger", MemberName: "Internal", RouteName: "logger.Internal", MethodID: methodIDLoggerInternal, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, Int64) Void", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: "Internal uses unnamed parameters to test ffigen's default naming (arg0, arg1, etc.)"},
}

func SurfaceLogger(impl Logger) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(loggerRoutes)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return loggerHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
