// Code generated by ffigen. DO NOT EDIT.
package e2e

import (
	"fmt"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_OS_Open = 1
	MethodID_OS_Name = 2
	MethodID_OS_Stat = 3
	MethodID_OS_Read = 4
	MethodID_OS_Write = 5
	MethodID_OS_Close = 6
	MethodID_OS_Deep = 7
)

type OSProxy struct {
	bridge ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *OSProxy) Open(name string) (*File, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(name)

	retData, err := p.bridge.Call(MethodID_OS_Open, buf.Bytes())
	if err != nil {
		return nil, err
	}

	retBuf := ffigo.NewReader(retData)
	var v_0 *File
		if id := retBuf.ReadUint32(); id != 0 {
			if p.registry != nil {
				if obj, ok := p.registry.Get(id); ok {
					v_0 = obj.(*File)
				}
			}
		}
	return v_0, nil
}

func (p *OSProxy) Name(f *File) (string) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

		if p.registry != nil {
			buf.WriteUint32(p.registry.Register(f))
		} else {
			buf.WriteUint32(0)
		}

	retData, err := p.bridge.Call(MethodID_OS_Name, buf.Bytes())
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = retBuf.ReadString()
	return v_0
}

func (p *OSProxy) Stat(f *File) (FileInfo, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

		if p.registry != nil {
			buf.WriteUint32(p.registry.Register(f))
		} else {
			buf.WriteUint32(0)
		}

	retData, err := p.bridge.Call(MethodID_OS_Stat, buf.Bytes())
	if err != nil {
		return FileInfo{}, err
	}

	retBuf := ffigo.NewReader(retData)
	var v_0 FileInfo
	v_0.Size = retBuf.ReadUint32()
	v_0.Name = retBuf.ReadString()
	return v_0, nil
}

func (p *OSProxy) Read(f *File, b []byte) (int, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

		if p.registry != nil {
			buf.WriteUint32(p.registry.Register(f))
		} else {
			buf.WriteUint32(0)
		}
	buf.WriteBytes(b)

	retData, err := p.bridge.Call(MethodID_OS_Read, buf.Bytes())
	if err != nil {
		return 0, err
	}

	retBuf := ffigo.NewReader(retData)
	var v_0 int
	v_0 = int(retBuf.ReadInt64())
	return v_0, nil
}

func (p *OSProxy) Write(f *File, b []byte) (int, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

		if p.registry != nil {
			buf.WriteUint32(p.registry.Register(f))
		} else {
			buf.WriteUint32(0)
		}
	buf.WriteBytes(b)

	retData, err := p.bridge.Call(MethodID_OS_Write, buf.Bytes())
	if err != nil {
		return 0, err
	}

	retBuf := ffigo.NewReader(retData)
	var v_0 int
	v_0 = int(retBuf.ReadInt64())
	return v_0, nil
}

func (p *OSProxy) Close(f *File) (error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

		if p.registry != nil {
			buf.WriteUint32(p.registry.Register(f))
		} else {
			buf.WriteUint32(0)
		}

	_, err := p.bridge.Call(MethodID_OS_Close, buf.Bytes())
	if err != nil {
		return err
	}

	return nil
}

func (p *OSProxy) Deep(n Nested) (Nested) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUint32(n.Info.Size)
	buf.WriteString(n.Info.Name)
	buf.WriteInt64(int64(n.Level))

	retData, err := p.bridge.Call(MethodID_OS_Deep, buf.Bytes())
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 Nested
	v_0.Info.Size = retBuf.ReadUint32()
	v_0.Info.Name = retBuf.ReadString()
	v_0.Level = int(retBuf.ReadInt64())
	return v_0
}

func OSHostRouter(impl OS, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_OS_Open:
		var name string
	name = reqBuf.ReadString()
		r0, err := impl.Open(name)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUint32(registry.Register(r0))
		return resBuf.Bytes(), err
	case MethodID_OS_Name:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		r0 := impl.Name(f)
		resBuf := ffigo.GetBuffer()
	resBuf.WriteString(r0)
		return resBuf.Bytes(), nil
	case MethodID_OS_Stat:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		r0, err := impl.Stat(f)
		resBuf := ffigo.GetBuffer()
	resBuf.WriteUint32(r0.Size)
	resBuf.WriteString(r0.Name)
		return resBuf.Bytes(), err
	case MethodID_OS_Read:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		var b []byte
	b = reqBuf.ReadBytes()
		r0, err := impl.Read(f, b)
		resBuf := ffigo.GetBuffer()
	resBuf.WriteInt64(int64(r0))
		return resBuf.Bytes(), err
	case MethodID_OS_Write:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		var b []byte
	b = reqBuf.ReadBytes()
		r0, err := impl.Write(f, b)
		resBuf := ffigo.GetBuffer()
	resBuf.WriteInt64(int64(r0))
		return resBuf.Bytes(), err
	case MethodID_OS_Close:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		err := impl.Close(f)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), err
	case MethodID_OS_Deep:
		var n Nested
	n.Info.Size = reqBuf.ReadUint32()
	n.Info.Name = reqBuf.ReadString()
	n.Level = int(reqBuf.ReadInt64())
		r0 := impl.Deep(n)
		resBuf := ffigo.GetBuffer()
	resBuf.WriteUint32(r0.Info.Size)
	resBuf.WriteString(r0.Info.Name)
	resBuf.WriteInt64(int64(r0.Level))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}
