// Code generated by ffigen. DO NOT EDIT.
package e2e

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"strings"
)

const (
	MethodID_PrinterAPI_Println = 1
)

type PrinterAPIProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *PrinterAPIProxy) Println(ctx context.Context, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUint32(uint32(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := p.bridge.Call(ctx, MethodID_PrinterAPI_Println, buf.Bytes())
	_ = err
	return
}

func PrinterAPIHostRouter(ctx context.Context, impl PrinterAPI, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_PrinterAPI_Println:
		var args []any
		l_args := int(reqBuf.ReadUint32())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			if id, ok := rawVal.(uint32); ok {
				if obj, ok := registry.Get(id); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rawVal
				}
			} else {
				args[i_args] = rawVal
			}
		}
		impl.Println(args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var PrinterAPI_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
}{
	{"Println", 1, "function(...Any) Void"},
}

type PrinterAPI_Bridge struct {
	Impl     PrinterAPI
	Registry *ffigo.HandleRegistry
}

func (b *PrinterAPI_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return PrinterAPIHostRouter(ctx, b.Impl, b.Registry, methodID, args)
}

func (b *PrinterAPI_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterE2EPrinterAPILibrary(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType)
}, prefix string, impl PrinterAPI, registry *ffigo.HandleRegistry) {
	bridge := &PrinterAPI_Bridge{Impl: impl, Registry: registry}
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range PrinterAPI_FFI_Metadata {
		executor.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec))
	}
}
