// Code generated by ffigen. DO NOT EDIT.
package e2e

import (
	"fmt"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_PrinterAPI_Println = 1
)

type PrinterAPIProxy struct {
	bridge ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *PrinterAPIProxy) Println(args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUint32(uint32(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := p.bridge.Call(MethodID_PrinterAPI_Println, buf.Bytes())
	_ = err
}

func PrinterAPIHostRouter(impl PrinterAPI, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_PrinterAPI_Println:
		var args []any
	l_args := int(reqBuf.ReadUint32())
	args = make([]any, l_args)
	for i_args := 0; i_args < l_args; i_args++ {
		args[i_args] = reqBuf.ReadAny()
	}
		impl.Println(args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}
