// Code generated by ffigen. DO NOT EDIT.
package fmtlib

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_Fmt_Print   = 1
	MethodID_Fmt_Println = 2
	MethodID_Fmt_Printf  = 3
	MethodID_Fmt_Sprintf = 4
)

type FmtProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *FmtProxy) Print(ctx context.Context, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUint32(uint32(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := p.bridge.Call(ctx, MethodID_Fmt_Print, buf.Bytes())
	_ = err
	return
}

func (p *FmtProxy) Println(ctx context.Context, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUint32(uint32(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := p.bridge.Call(ctx, MethodID_Fmt_Println, buf.Bytes())
	_ = err
	return
}

func (p *FmtProxy) Printf(ctx context.Context, format string, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(format)
	buf.WriteUint32(uint32(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := p.bridge.Call(ctx, MethodID_Fmt_Printf, buf.Bytes())
	_ = err
	return
}

func (p *FmtProxy) Sprintf(ctx context.Context, format string, args ...any) string {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(format)
	buf.WriteUint32(uint32(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	retData, err := p.bridge.Call(ctx, MethodID_Fmt_Sprintf, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = retBuf.ReadString()
	return v_0
}

func FmtHostRouter(ctx context.Context, impl Fmt, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Fmt_Print:
		var args []any
		l_args := int(reqBuf.ReadUint32())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			if id, ok := rawVal.(uint32); ok {
				if obj, ok := registry.Get(id); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rawVal
				}
			} else {
				args[i_args] = rawVal
			}
		}
		impl.Print(args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Println:
		var args []any
		l_args := int(reqBuf.ReadUint32())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			if id, ok := rawVal.(uint32); ok {
				if obj, ok := registry.Get(id); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rawVal
				}
			} else {
				args[i_args] = rawVal
			}
		}
		impl.Println(args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Printf:
		var format string
		format = reqBuf.ReadString()
		var args []any
		l_args := int(reqBuf.ReadUint32())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			if id, ok := rawVal.(uint32); ok {
				if obj, ok := registry.Get(id); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rawVal
				}
			} else {
				args[i_args] = rawVal
			}
		}
		impl.Printf(format, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Sprintf:
		var format string
		format = reqBuf.ReadString()
		var args []any
		l_args := int(reqBuf.ReadUint32())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			if id, ok := rawVal.(uint32); ok {
				if obj, ok := registry.Get(id); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rawVal
				}
			} else {
				args[i_args] = rawVal
			}
		}
		r0 := impl.Sprintf(format, args...)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(r0)
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Fmt_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
}{
	{"Print", 1, "function(...Any) Void"},
	{"Println", 2, "function(...Any) Void"},
	{"Printf", 3, "function(String, ...Any) Void"},
	{"Sprintf", 4, "function(String, ...Any) String"},
}

type Fmt_Bridge struct {
	Impl     Fmt
	Registry *ffigo.HandleRegistry
}

func (b *Fmt_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return FmtHostRouter(ctx, b.Impl, b.Registry, methodID, args)
}

func (b *Fmt_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterFMTLIBFmtLibrary(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType)
}, prefix string, impl Fmt, registry *ffigo.HandleRegistry) {
	bridge := &Fmt_Bridge{Impl: impl, Registry: registry}
	for _, m := range Fmt_FFI_Metadata {
		executor.RegisterFFI(prefix+"."+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec))
	}
}
