// Code generated by ffigen. DO NOT EDIT.
package fmtlib

import (
	"context"
	"fmt"
	"strings"
)
import (
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_Fmt_Print    = 1
	MethodID_Fmt_Println  = 2
	MethodID_Fmt_Printf   = 3
	MethodID_Fmt_Sprintf  = 4
	MethodID_Fmt_Fprint   = 5
	MethodID_Fmt_Fprintf  = 6
	MethodID_Fmt_Fprintln = 7
)

type FmtProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewFmtProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) Fmt {
	return &FmtProxy{bridge: bridge, registry: registry}
}

func (__p *FmtProxy) Print(args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Print, buf.Bytes())
	_ = err
	return
}

func (__p *FmtProxy) Println(args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Println, buf.Bytes())
	_ = err
	return
}

func (__p *FmtProxy) Printf(format string, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(string(format))
	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Printf, buf.Bytes())
	_ = err
	return
}

func (__p *FmtProxy) Sprintf(format string, args ...any) string {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(string(format))
	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	retData, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Sprintf, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *FmtProxy) Fprint(w any, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(w)
	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Fprint, buf.Bytes())
	_ = err
	return
}

func (__p *FmtProxy) Fprintf(w any, format string, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(w)
	buf.WriteString(string(format))
	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Fprintf, buf.Bytes())
	_ = err
	return
}

func (__p *FmtProxy) Fprintln(w any, args ...any) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(w)
	buf.WriteUvarint(uint64(len(args)))
	for _, item := range args {
		buf.WriteAny(item)
	}

	_, err := __p.bridge.Call(context.Background(), MethodID_Fmt_Fprintln, buf.Bytes())
	_ = err
	return
}

func FmtHostRouter(ctx context.Context, impl Fmt, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) ([]byte, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Print":
			methodID = MethodID_Fmt_Print
		case "Println":
			methodID = MethodID_Fmt_Println
		case "Printf":
			methodID = MethodID_Fmt_Printf
		case "Sprintf":
			methodID = MethodID_Fmt_Sprintf
		case "Fprint":
			methodID = MethodID_Fmt_Fprint
		case "Fprintf":
			methodID = MethodID_Fmt_Fprintf
		case "Fprintln":
			methodID = MethodID_Fmt_Fprintln
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Fmt_Print:
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		impl.Print(args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Println:
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		impl.Println(args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Printf:
		var format string
		format = string(reqBuf.ReadString())
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		impl.Printf(format, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Sprintf:
		var format string
		format = string(reqBuf.ReadString())
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		r0 := impl.Sprintf(format, args...)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Fprint:
		var w any
		rawVal := reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, ok := registry.Get(rv); ok {
				w = obj
			} else {
				w = rv
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, ok := registry.Get(rv.Handle); ok {
					w = obj
				} else {
					w = rv
				}
			} else {
				w = rv
			}
		default:
			w = rawVal
		}
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		impl.Fprint(w, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Fprintf:
		var w any
		rawVal := reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, ok := registry.Get(rv); ok {
				w = obj
			} else {
				w = rv
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, ok := registry.Get(rv.Handle); ok {
					w = obj
				} else {
					w = rv
				}
			} else {
				w = rv
			}
		default:
			w = rawVal
		}
		var format string
		format = string(reqBuf.ReadString())
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		impl.Fprintf(w, format, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Fmt_Fprintln:
		var w any
		rawVal := reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, ok := registry.Get(rv); ok {
				w = obj
			} else {
				w = rv
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, ok := registry.Get(rv.Handle); ok {
					w = obj
				} else {
					w = rv
				}
			} else {
				w = rv
			}
		default:
			w = rawVal
		}
		var args []any
		l_args := int(reqBuf.ReadUvarint())
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal := reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case uint32:
				if obj, ok := registry.Get(rv); ok {
					args[i_args] = obj
				} else {
					args[i_args] = rv
				}
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					if obj, ok := registry.Get(rv.Handle); ok {
						args[i_args] = obj
					} else {
						args[i_args] = rv
					}
				} else {
					args[i_args] = rv
				}
			default:
				args[i_args] = rawVal
			}
		}
		impl.Fprintln(w, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Fmt_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
	Doc      string
}{
	{"Print", 1, "function(...Any) Void", ""},
	{"Println", 2, "function(...Any) Void", ""},
	{"Printf", 3, "function(String, ...Any) Void", ""},
	{"Sprintf", 4, "function(String, ...Any) String", ""},
	{"Fprint", 5, "function(Any, ...Any) Void", ""},
	{"Fprintf", 6, "function(Any, String, ...Any) Void", ""},
	{"Fprintln", 7, "function(Any, ...Any) Void", ""},
}

type Fmt_Bridge struct {
	Impl     Fmt
	Registry *ffigo.HandleRegistry
}

func (b *Fmt_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return FmtHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *Fmt_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return FmtHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *Fmt_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterFmt(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType, string)
	RegisterStructSpec(string, ast.GoMiniType)
}, impl Fmt, registry *ffigo.HandleRegistry) {
	bridge := &Fmt_Bridge{Impl: impl, Registry: registry}
	prefix := "fmt"
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range Fmt_FFI_Metadata {
		executor.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec), m.Doc)
	}
}
