// Code generated by ffigen. DO NOT EDIT.
package synclib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

var sync_WaitGroup_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("sync.WaitGroup", runtime.StructOwnershipHostOpaque, "struct { Add function(HostRef<sync.WaitGroup>, Int64) Void; Done function(HostRef<sync.WaitGroup>) Void; Wait function(HostRef<sync.WaitGroup>) Void; }")

const (
	MethodID_Module_NewWaitGroup = 1
)

type ModuleProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewModuleProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) Module {
	return &ModuleProxy{bridge: bridge, registry: registry}
}

func (__p *ModuleProxy) NewWaitGroup() *WaitGroup {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Module_NewWaitGroup, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 *WaitGroup
	// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.GetTyped(id, "sync.WaitGroup"); ok {
				v_0 = obj.(*WaitGroup)
			}
		}
	}
	return v_0
}

func ModuleHostRouter(ctx context.Context, impl Module, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "NewWaitGroup":
			methodID = MethodID_Module_NewWaitGroup
		}
	}

	switch methodID {
	case MethodID_Module_NewWaitGroup:
		r0 := impl.NewWaitGroup()
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "sync.WaitGroup")))
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Module_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"NewWaitGroup", 1, runtime.MustParseRuntimeFuncSig("function() HostRef<sync.WaitGroup>"), ""},
}

type Module_Bridge struct {
	Impl     Module
	Registry *ffigo.HandleRegistry
}

func (b *Module_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ModuleHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Module_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ModuleHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Module_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterModule(executor interface{ RegisterConstant(string, string) }, impl Module, registry *ffigo.HandleRegistry) {
	bridge := &Module_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registrar.RegisterFFISchema("sync.NewWaitGroup", bridge, Module_FFI_Schemas[0].MethodID, Module_FFI_Schemas[0].Sig, Module_FFI_Schemas[0].Doc)
}

const (
	MethodID_WaitGroup_Add  = 1
	MethodID_WaitGroup_Done = 2
	MethodID_WaitGroup_Wait = 3
)

func WaitGroupHostRouter(ctx context.Context, impl *WaitGroup, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Add":
			methodID = MethodID_WaitGroup_Add
		case "Done":
			methodID = MethodID_WaitGroup_Done
		case "Wait":
			methodID = MethodID_WaitGroup_Wait
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_WaitGroup_Add:
		var __recv *WaitGroup
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "sync.WaitGroup"); err == nil {
				__recv = obj.(*WaitGroup)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var delta int64
		{
			tmp := reqBuf.ReadVarint()
			delta = int64(tmp)
		}
		__recv.Add(delta)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_WaitGroup_Done:
		var __recv *WaitGroup
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "sync.WaitGroup"); err == nil {
				__recv = obj.(*WaitGroup)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		__recv.Done()
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_WaitGroup_Wait:
		var __recv *WaitGroup
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "sync.WaitGroup"); err == nil {
				__recv = obj.(*WaitGroup)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Wait()
		return ffigo.AsyncValue[ffigo.Void](r0, func(resBuf *ffigo.Buffer, value ffigo.Void) error {
			return nil
		}), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var WaitGroup_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Add", 1, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<sync.WaitGroup>, Int64) Void", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Done", 2, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<sync.WaitGroup>) Void", runtime.FFIParamIn), ""},
	{"Wait", 3, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<sync.WaitGroup>) Void", runtime.FFIParamIn), ""},
}

type WaitGroup_Bridge struct {
	Impl     *WaitGroup
	Registry *ffigo.HandleRegistry
}

func (b *WaitGroup_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return WaitGroupHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *WaitGroup_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return WaitGroupHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *WaitGroup_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterWaitGroup(executor interface{ RegisterConstant(string, string) }, registry *ffigo.HandleRegistry) {
	bridge := &WaitGroup_Bridge{Impl: nil, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("sync.WaitGroup.Add", bridge, WaitGroup_FFI_Schemas[0].MethodID, WaitGroup_FFI_Schemas[0].Sig, WaitGroup_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("sync.WaitGroup.Done", bridge, WaitGroup_FFI_Schemas[1].MethodID, WaitGroup_FFI_Schemas[1].Sig, WaitGroup_FFI_Schemas[1].Doc)
	registrar.RegisterFFISchema("sync.WaitGroup.Wait", bridge, WaitGroup_FFI_Schemas[2].MethodID, WaitGroup_FFI_Schemas[2].Sig, WaitGroup_FFI_Schemas[2].Doc)
	registerStructSchema("sync.WaitGroup", sync_WaitGroup_FFI_StructSchema)
}
