// Code generated by ffigen. DO NOT EDIT.
package timelib

import (
	"context"
	"fmt"
	"time"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

var time_Time_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("time.Time", runtime.StructOwnershipHostOpaque, "struct { Year function(HostRef<time.Time>) Int64; Month function(HostRef<time.Time>) Int64; Day function(HostRef<time.Time>) Int64; Hour function(HostRef<time.Time>) Int64; Minute function(HostRef<time.Time>) Int64; Second function(HostRef<time.Time>) Int64; Nanosecond function(HostRef<time.Time>) Int64; Unix function(HostRef<time.Time>) Int64; UnixMilli function(HostRef<time.Time>) Int64; UnixMicro function(HostRef<time.Time>) Int64; UnixNano function(HostRef<time.Time>) Int64; Format function(HostRef<time.Time>, String) String; Add function(HostRef<time.Time>, Int64) HostRef<time.Time>; Sub function(HostRef<time.Time>, HostRef<time.Time>) Int64; IsZero function(HostRef<time.Time>) Bool; Before function(HostRef<time.Time>, HostRef<time.Time>) Bool; After function(HostRef<time.Time>, HostRef<time.Time>) Bool; Equal function(HostRef<time.Time>, HostRef<time.Time>) Bool; String function(HostRef<time.Time>) String; }")

const (
	methodIDModuleNow           = 1
	methodIDModuleUnix          = 2
	methodIDModuleSleep         = 3
	methodIDModuleSince         = 4
	methodIDModuleUntil         = 5
	methodIDModuleParse         = 6
	methodIDModuleParseDuration = 7
)

func moduleHostRouter(ctx context.Context, impl Module, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Now":
			methodID = methodIDModuleNow
		case "Unix":
			methodID = methodIDModuleUnix
		case "Sleep":
			methodID = methodIDModuleSleep
		case "Since":
			methodID = methodIDModuleSince
		case "Until":
			methodID = methodIDModuleUntil
		case "Parse":
			methodID = methodIDModuleParse
		case "ParseDuration":
			methodID = methodIDModuleParseDuration
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDModuleNow:
		r0 := impl.Now(ctx)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "time.Time")))
		}
		return resBuf.Bytes(), nil
	case methodIDModuleUnix:
		var sec int64
		{
			tmp := reqBuf.ReadVarint()
			sec = int64(tmp)
		}
		var nsec int64
		{
			tmp := reqBuf.ReadVarint()
			nsec = int64(tmp)
		}
		r0 := impl.Unix(sec, nsec)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "time.Time")))
		}
		return resBuf.Bytes(), nil
	case methodIDModuleSleep:
		var ns int64
		{
			tmp := reqBuf.ReadVarint()
			ns = int64(tmp)
		}
		r0 := impl.Sleep(ctx, ns)
		return ffigo.AsyncValue[ffigo.Void](r0, func(resBuf *ffigo.Buffer, value ffigo.Void) error {
			return nil
		}), nil
	case methodIDModuleSince:
		var t *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				t = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "t", err)
			}
		}
		r0 := impl.Since(ctx, t)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDModuleUntil:
		var t *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				t = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "t", err)
			}
		}
		r0 := impl.Until(ctx, t)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDModuleParse:
		var layout string
		layout = string(reqBuf.ReadString())
		var value string
		value = string(reqBuf.ReadString())
		r0, err := impl.Parse(layout, value)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "time.Time")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDModuleParseDuration:
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.ParseDuration(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var moduleRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "time", MemberName: "Now", RouteName: "time.Now", MethodID: methodIDModuleNow, Sig: runtime.MustParseRuntimeFuncSig("function() HostRef<time.Time>"), Doc: ""},
	{PackagePath: "time", MemberName: "Unix", RouteName: "time.Unix", MethodID: methodIDModuleUnix, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Int64, Int64) HostRef<time.Time>", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "time", MemberName: "Sleep", RouteName: "time.Sleep", MethodID: methodIDModuleSleep, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Int64) Void", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "time", MemberName: "Since", RouteName: "time.Since", MethodID: methodIDModuleSince, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "time", MemberName: "Until", RouteName: "time.Until", MethodID: methodIDModuleUntil, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "time", MemberName: "Parse", RouteName: "time.Parse", MethodID: methodIDModuleParse, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String) tuple(HostRef<time.Time>, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "time", MemberName: "ParseDuration", RouteName: "time.ParseDuration", MethodID: methodIDModuleParseDuration, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(Int64, Error)", runtime.FFIParamIn), Doc: ""},
}

func SurfaceModule(impl Module) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(moduleRoutes)
	schema.AddConst("time", "ANSIC", runtime.MustConstantValue(time.ANSIC))
	schema.AddConst("time", "Hour", runtime.MustConstantValue(time.Hour))
	schema.AddConst("time", "Kitchen", runtime.MustConstantValue(time.Kitchen))
	schema.AddConst("time", "Layout", runtime.MustConstantValue(time.Layout))
	schema.AddConst("time", "Microsecond", runtime.MustConstantValue(time.Microsecond))
	schema.AddConst("time", "Millisecond", runtime.MustConstantValue(time.Millisecond))
	schema.AddConst("time", "Minute", runtime.MustConstantValue(time.Minute))
	schema.AddConst("time", "Nanosecond", runtime.MustConstantValue(time.Nanosecond))
	schema.AddConst("time", "RFC1123", runtime.MustConstantValue(time.RFC1123))
	schema.AddConst("time", "RFC1123Z", runtime.MustConstantValue(time.RFC1123Z))
	schema.AddConst("time", "RFC3339", runtime.MustConstantValue(time.RFC3339))
	schema.AddConst("time", "RFC3339Nano", runtime.MustConstantValue(time.RFC3339Nano))
	schema.AddConst("time", "RFC822", runtime.MustConstantValue(time.RFC822))
	schema.AddConst("time", "RFC822Z", runtime.MustConstantValue(time.RFC822Z))
	schema.AddConst("time", "RFC850", runtime.MustConstantValue(time.RFC850))
	schema.AddConst("time", "RubyDate", runtime.MustConstantValue(time.RubyDate))
	schema.AddConst("time", "Second", runtime.MustConstantValue(time.Second))
	schema.AddConst("time", "UnixDate", runtime.MustConstantValue(time.UnixDate))
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return moduleHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}

const (
	methodIDTimeYear       = 1
	methodIDTimeMonth      = 2
	methodIDTimeDay        = 3
	methodIDTimeHour       = 4
	methodIDTimeMinute     = 5
	methodIDTimeSecond     = 6
	methodIDTimeNanosecond = 7
	methodIDTimeUnix       = 8
	methodIDTimeUnixMilli  = 9
	methodIDTimeUnixMicro  = 10
	methodIDTimeUnixNano   = 11
	methodIDTimeFormat     = 12
	methodIDTimeAdd        = 13
	methodIDTimeSub        = 14
	methodIDTimeIsZero     = 15
	methodIDTimeBefore     = 16
	methodIDTimeAfter      = 17
	methodIDTimeEqual      = 18
	methodIDTimeString     = 19
)

func timeHostRouter(ctx context.Context, impl *Time, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Year":
			methodID = methodIDTimeYear
		case "Month":
			methodID = methodIDTimeMonth
		case "Day":
			methodID = methodIDTimeDay
		case "Hour":
			methodID = methodIDTimeHour
		case "Minute":
			methodID = methodIDTimeMinute
		case "Second":
			methodID = methodIDTimeSecond
		case "Nanosecond":
			methodID = methodIDTimeNanosecond
		case "Unix":
			methodID = methodIDTimeUnix
		case "UnixMilli":
			methodID = methodIDTimeUnixMilli
		case "UnixMicro":
			methodID = methodIDTimeUnixMicro
		case "UnixNano":
			methodID = methodIDTimeUnixNano
		case "Format":
			methodID = methodIDTimeFormat
		case "Add":
			methodID = methodIDTimeAdd
		case "Sub":
			methodID = methodIDTimeSub
		case "IsZero":
			methodID = methodIDTimeIsZero
		case "Before":
			methodID = methodIDTimeBefore
		case "After":
			methodID = methodIDTimeAfter
		case "Equal":
			methodID = methodIDTimeEqual
		case "String":
			methodID = methodIDTimeString
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDTimeYear:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Year()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeMonth:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Month()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeDay:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Day()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeHour:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Hour()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeMinute:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Minute()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeSecond:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Second()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeNanosecond:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Nanosecond()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeUnix:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Unix()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeUnixMilli:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.UnixMilli()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeUnixMicro:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.UnixMicro()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeUnixNano:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.UnixNano()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeFormat:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var layout string
		layout = string(reqBuf.ReadString())
		r0 := __recv.Format(layout)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeAdd:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var d int64
		{
			tmp := reqBuf.ReadVarint()
			d = int64(tmp)
		}
		r0 := __recv.Add(d)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "time.Time")))
		}
		return resBuf.Bytes(), nil
	case methodIDTimeSub:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var other *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				other = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "other", err)
			}
		}
		r0 := __recv.Sub(other)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeIsZero:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.IsZero()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeBefore:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var other *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				other = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "other", err)
			}
		}
		r0 := __recv.Before(other)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeAfter:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var other *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				other = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "other", err)
			}
		}
		r0 := __recv.After(other)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeEqual:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var other *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				other = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "other", err)
			}
		}
		r0 := __recv.Equal(other)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	case methodIDTimeString:
		var __recv *Time
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "time.Time"); err == nil {
				__recv = obj.(*Time)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.String()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var timeRoutes = []runtime.FFIRouteDecl{
	{TypeName: "time.Time", MethodName: "Year", RouteName: "time.Time.Year", MethodID: methodIDTimeYear, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Month", RouteName: "time.Time.Month", MethodID: methodIDTimeMonth, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Day", RouteName: "time.Time.Day", MethodID: methodIDTimeDay, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Hour", RouteName: "time.Time.Hour", MethodID: methodIDTimeHour, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Minute", RouteName: "time.Time.Minute", MethodID: methodIDTimeMinute, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Second", RouteName: "time.Time.Second", MethodID: methodIDTimeSecond, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Nanosecond", RouteName: "time.Time.Nanosecond", MethodID: methodIDTimeNanosecond, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Unix", RouteName: "time.Time.Unix", MethodID: methodIDTimeUnix, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "UnixMilli", RouteName: "time.Time.UnixMilli", MethodID: methodIDTimeUnixMilli, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "UnixMicro", RouteName: "time.Time.UnixMicro", MethodID: methodIDTimeUnixMicro, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "UnixNano", RouteName: "time.Time.UnixNano", MethodID: methodIDTimeUnixNano, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Int64", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Format", RouteName: "time.Time.Format", MethodID: methodIDTimeFormat, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>, String) String", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Add", RouteName: "time.Time.Add", MethodID: methodIDTimeAdd, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>, Int64) HostRef<time.Time>", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Sub", RouteName: "time.Time.Sub", MethodID: methodIDTimeSub, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>, HostRef<time.Time>) Int64", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "IsZero", RouteName: "time.Time.IsZero", MethodID: methodIDTimeIsZero, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) Bool", runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Before", RouteName: "time.Time.Before", MethodID: methodIDTimeBefore, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>, HostRef<time.Time>) Bool", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "After", RouteName: "time.Time.After", MethodID: methodIDTimeAfter, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>, HostRef<time.Time>) Bool", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "Equal", RouteName: "time.Time.Equal", MethodID: methodIDTimeEqual, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>, HostRef<time.Time>) Bool", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{TypeName: "time.Time", MethodName: "String", RouteName: "time.Time.String", MethodID: methodIDTimeString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<time.Time>) String", runtime.FFIParamIn), Doc: ""},
}

func SurfaceTime() *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(timeRoutes)
	schema.AddStruct("time.Time", time_Time_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return timeHostRouter(callCtx, nil, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
