// Code generated by ffigen. DO NOT EDIT.
package jsonlib

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"strings"
)

const (
	MethodID_JSON_Marshal   = 1
	MethodID_JSON_Unmarshal = 2
)

type JSONProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewJSONProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) JSON {
	return &JSONProxy{bridge: bridge, registry: registry}
}

func (__p *JSONProxy) Marshal(v any) ([]byte, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(v)

	retData, err := __p.bridge.Call(context.Background(), MethodID_JSON_Marshal, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *JSONProxy) Unmarshal(data []byte) (any, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteBytes(data)

	retData, err := __p.bridge.Call(context.Background(), MethodID_JSON_Unmarshal, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 any
	v_0 = retBuf.ReadAny()
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func JSONHostRouter(ctx context.Context, impl JSON, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) ([]byte, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Marshal":
			methodID = MethodID_JSON_Marshal
		case "Unmarshal":
			methodID = MethodID_JSON_Unmarshal
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_JSON_Marshal:
		var v any
		rawVal := reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, ok := registry.Get(rv); ok {
				v = obj
			} else {
				v = rv
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, ok := registry.Get(rv.Handle); ok {
					v = obj
				} else {
					v = rv
				}
			} else {
				v = rv
			}
		default:
			v = rawVal
		}
		r0, err := impl.Marshal(v)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_JSON_Unmarshal:
		var data []byte
		data = reqBuf.ReadBytes()
		r0, err := impl.Unmarshal(data)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteAny(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var JSON_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
	Doc      string
}{
	{"Marshal", 1, "function(Any) tuple(TypeBytes, Error)", ""},
	{"Unmarshal", 2, "function(TypeBytes) tuple(Any, Error)", ""},
}

type JSON_Bridge struct {
	Impl     JSON
	Registry *ffigo.HandleRegistry
}

func (b *JSON_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return JSONHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *JSON_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return JSONHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *JSON_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterJSON(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType, string)
}, impl JSON, registry *ffigo.HandleRegistry) {
	bridge := &JSON_Bridge{Impl: impl, Registry: registry}
	prefix := "json"
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range JSON_FFI_Metadata {
		executor.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec), m.Doc)
	}
}
