// Code generated by ffigen. DO NOT EDIT.
package jsonlib

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_JSON_Marshal = 1
	MethodID_JSON_Unmarshal = 2
)

type JSONProxy struct {
	bridge ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *JSONProxy) Marshal(ctx context.Context, v any) ([]byte, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(v)

	retData, err := p.bridge.Call(ctx, MethodID_JSON_Marshal, buf.Bytes())
	_ = retData
	if err != nil { return nil, err }
	retBuf := ffigo.NewReader(retData)
	status := retBuf.ReadByte()
	if status != 0 {
		errMsg := retBuf.ReadString()
		return nil, fmt.Errorf("%s", errMsg)
	}
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	return v_0, nil
}

func (p *JSONProxy) Unmarshal(ctx context.Context, data []byte) (any, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteBytes(data)

	retData, err := p.bridge.Call(ctx, MethodID_JSON_Unmarshal, buf.Bytes())
	_ = retData
	if err != nil { return nil, err }
	retBuf := ffigo.NewReader(retData)
	status := retBuf.ReadByte()
	if status != 0 {
		errMsg := retBuf.ReadString()
		return nil, fmt.Errorf("%s", errMsg)
	}
	var v_0 any
	v_0 = retBuf.ReadAny()
	return v_0, nil
}

func JSONHostRouter(ctx context.Context, impl JSON, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	_ = reqBuf
	switch methodID {
	case MethodID_JSON_Marshal:
		var v any
		rawVal := reqBuf.ReadAny()
		if id, ok := rawVal.(uint32); ok {
			if obj, ok := registry.Get(id); ok {
				v = obj
			} else {
				v = rawVal
			}
		} else {
			v = rawVal
		}
		r0, err := impl.Marshal(v)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			resBuf.WriteByte(1)
			resBuf.WriteString(err.Error())
		} else {
			resBuf.WriteByte(0)
	resBuf.WriteBytes(r0)
		}
		return resBuf.Bytes(), nil
	case MethodID_JSON_Unmarshal:
		var data []byte
	data = reqBuf.ReadBytes()
		r0, err := impl.Unmarshal(data)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			resBuf.WriteByte(1)
			resBuf.WriteString(err.Error())
		} else {
			resBuf.WriteByte(0)
	resBuf.WriteAny(r0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}
