// Code generated by ffigen. DO NOT EDIT.
package regexplib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDRegexpMatch                   = 1
	methodIDRegexpMatchString             = 2
	methodIDRegexpQuoteMeta               = 3
	methodIDRegexpFindString              = 4
	methodIDRegexpFindAllString           = 5
	methodIDRegexpFindStringIndex         = 6
	methodIDRegexpFindStringSubmatchIndex = 7
	methodIDRegexpFindStringSubmatch      = 8
	methodIDRegexpFindAllStringSubmatch   = 9
	methodIDRegexpReplaceAllString        = 10
	methodIDRegexpReplaceAllLiteralString = 11
	methodIDRegexpSplit                   = 12
)

func regexpHostRouter(ctx context.Context, impl Regexp, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Match":
			methodID = methodIDRegexpMatch
		case "MatchString":
			methodID = methodIDRegexpMatchString
		case "QuoteMeta":
			methodID = methodIDRegexpQuoteMeta
		case "FindString":
			methodID = methodIDRegexpFindString
		case "FindAllString":
			methodID = methodIDRegexpFindAllString
		case "FindStringIndex":
			methodID = methodIDRegexpFindStringIndex
		case "FindStringSubmatchIndex":
			methodID = methodIDRegexpFindStringSubmatchIndex
		case "FindStringSubmatch":
			methodID = methodIDRegexpFindStringSubmatch
		case "FindAllStringSubmatch":
			methodID = methodIDRegexpFindAllStringSubmatch
		case "ReplaceAllString":
			methodID = methodIDRegexpReplaceAllString
		case "ReplaceAllLiteralString":
			methodID = methodIDRegexpReplaceAllLiteralString
		case "Split":
			methodID = methodIDRegexpSplit
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDRegexpMatch:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Match(pattern, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpMatchString:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.MatchString(pattern, s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpQuoteMeta:
		var s string
		s = string(reqBuf.ReadString())
		r0 := impl.QuoteMeta(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDRegexpFindString:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		r0 := impl.FindString(pattern, s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDRegexpFindAllString:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		var n int
		{
			tmp := reqBuf.ReadVarint()
			n = int(tmp)
		}
		r0, err := impl.FindAllString(pattern, s, n)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for _, item := range r0 {
			resBuf.WriteString(string(item))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpFindStringIndex:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.FindStringIndex(pattern, s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for _, item := range r0 {
			resBuf.WriteVarint(int64(item))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpFindStringSubmatchIndex:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.FindStringSubmatchIndex(pattern, s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for _, item := range r0 {
			resBuf.WriteVarint(int64(item))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpFindStringSubmatch:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		r0 := impl.FindStringSubmatch(pattern, s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for _, item := range r0 {
			resBuf.WriteString(string(item))
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpFindAllStringSubmatch:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		var n int
		{
			tmp := reqBuf.ReadVarint()
			n = int(tmp)
		}
		r0, err := impl.FindAllStringSubmatch(pattern, s, n)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for _, item := range r0 {
			resBuf.WriteUvarint(uint64(len(item)))
			for _, item := range item {
				resBuf.WriteString(string(item))
			}
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpReplaceAllString:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var src string
		src = string(reqBuf.ReadString())
		var repl string
		repl = string(reqBuf.ReadString())
		r0, err := impl.ReplaceAllString(pattern, src, repl)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpReplaceAllLiteralString:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var src string
		src = string(reqBuf.ReadString())
		var repl string
		repl = string(reqBuf.ReadString())
		r0, err := impl.ReplaceAllLiteralString(pattern, src, repl)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDRegexpSplit:
		var pattern string
		pattern = string(reqBuf.ReadString())
		var s string
		s = string(reqBuf.ReadString())
		var n int
		{
			tmp := reqBuf.ReadVarint()
			n = int(tmp)
		}
		r0, err := impl.Split(pattern, s, n)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUvarint(uint64(len(r0)))
		for _, item := range r0 {
			resBuf.WriteString(string(item))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var regexpRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "regexp", MemberName: "Match", RouteName: "regexp.Match", MethodID: methodIDRegexpMatch, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, TypeBytes) tuple(Bool, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "MatchString", RouteName: "regexp.MatchString", MethodID: methodIDRegexpMatchString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String) tuple(Bool, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "QuoteMeta", RouteName: "regexp.QuoteMeta", MethodID: methodIDRegexpQuoteMeta, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "FindString", RouteName: "regexp.FindString", MethodID: methodIDRegexpFindString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String) String", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "FindAllString", RouteName: "regexp.FindAllString", MethodID: methodIDRegexpFindAllString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, Int64) tuple(Array<String>, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "FindStringIndex", RouteName: "regexp.FindStringIndex", MethodID: methodIDRegexpFindStringIndex, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String) tuple(Array<Int64>, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "FindStringSubmatchIndex", RouteName: "regexp.FindStringSubmatchIndex", MethodID: methodIDRegexpFindStringSubmatchIndex, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String) tuple(Array<Int64>, Error)", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "FindStringSubmatch", RouteName: "regexp.FindStringSubmatch", MethodID: methodIDRegexpFindStringSubmatch, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String) Array<String>", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "FindAllStringSubmatch", RouteName: "regexp.FindAllStringSubmatch", MethodID: methodIDRegexpFindAllStringSubmatch, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, Int64) tuple(Array<Array<String>>, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "ReplaceAllString", RouteName: "regexp.ReplaceAllString", MethodID: methodIDRegexpReplaceAllString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, String) tuple(String, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "ReplaceAllLiteralString", RouteName: "regexp.ReplaceAllLiteralString", MethodID: methodIDRegexpReplaceAllLiteralString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, String) tuple(String, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "regexp", MemberName: "Split", RouteName: "regexp.Split", MethodID: methodIDRegexpSplit, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, String, Int64) tuple(Array<String>, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
}

func SurfaceRegexp(impl Regexp) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(regexpRoutes)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return regexpHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
