// Code generated by ffigen. DO NOT EDIT.
package storagelib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	MethodID_StorageAPI_SetCapacity = 1
	MethodID_StorageAPI_GetStatus   = 2
)

type StorageAPIProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewStorageAPIProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) StorageAPI {
	return &StorageAPIProxy{bridge: bridge, registry: registry}
}

func (__p *StorageAPIProxy) SetCapacity(capacity uint32) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteVarint(int64(capacity))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_StorageAPI_SetCapacity, Args: append([]byte(nil), wireBuf.Bytes()...)})
	if syncErr := func() error { _, syncErr := ffigo.SyncBytes(__ret); return syncErr }(); err == nil {
		err = syncErr
	}
	_ = err
	return
}

func (__p *StorageAPIProxy) GetStatus() int16 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_StorageAPI_GetStatus, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 int16
	{
		tmp := retBuf.ReadVarint()
		if tmp < -32768 || tmp > 32767 {
			panic(fmt.Sprintf("ffi: int16 overflow: %d", tmp))
		}
		v_0 = int16(tmp)
	}
	return v_0
}

func StorageAPIHostRouter(ctx context.Context, impl StorageAPI, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "SetCapacity":
			methodID = MethodID_StorageAPI_SetCapacity
		case "GetStatus":
			methodID = MethodID_StorageAPI_GetStatus
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_StorageAPI_SetCapacity:
		var capacity uint32
		{
			tmp := reqBuf.ReadVarint()
			if tmp < 0 || tmp > 4294967295 {
				panic(fmt.Sprintf("ffi: uint32 overflow: %d", tmp))
			}
			capacity = uint32(tmp)
		}
		impl.SetCapacity(capacity)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_StorageAPI_GetStatus:
		r0 := impl.GetStatus()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var StorageAPI_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"SetCapacity", 1, runtime.MustParseRuntimeFuncSigWithModes("function(Int64) Void", runtime.FFIParamIn), ""},
	{"GetStatus", 2, runtime.MustParseRuntimeFuncSig("function() Int64"), ""},
}

type StorageAPI_Bridge struct {
	Impl     StorageAPI
	Registry *ffigo.HandleRegistry
}

func (b *StorageAPI_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return StorageAPIHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *StorageAPI_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return StorageAPIHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *StorageAPI_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceStorageAPI(impl StorageAPI) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddFunc("storage", "SetCapacity", "storage.SetCapacity", StorageAPI_FFI_Schemas[0].MethodID, StorageAPI_FFI_Schemas[0].Sig, StorageAPI_FFI_Schemas[0].Doc)
	schema.AddFunc("storage", "GetStatus", "storage.GetStatus", StorageAPI_FFI_Schemas[1].MethodID, StorageAPI_FFI_Schemas[1].Sig, StorageAPI_FFI_Schemas[1].Doc)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &StorageAPI_Bridge{Impl: impl, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.AddRoute("storage", "SetCapacity", runtime.FFIRoute{Name: "storage.SetCapacity", Bridge: bridge, MethodID: StorageAPI_FFI_Schemas[0].MethodID, FuncSig: StorageAPI_FFI_Schemas[0].Sig, Doc: StorageAPI_FFI_Schemas[0].Doc})
		bound.AddRoute("storage", "GetStatus", runtime.FFIRoute{Name: "storage.GetStatus", Bridge: bridge, MethodID: StorageAPI_FFI_Schemas[1].MethodID, FuncSig: StorageAPI_FFI_Schemas[1].Sig, Doc: StorageAPI_FFI_Schemas[1].Doc})
		return bound, nil
	})
}
