// Code generated by ffigen. DO NOT EDIT.
package iolib

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"strings"
)

const (
	MethodID_IO_ReadAll = 1
)

type IOProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *IOProxy) ReadAll(ctx context.Context, r any) ([]byte, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(r)

	retData, err := p.bridge.Call(ctx, MethodID_IO_ReadAll, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	var err_1 error
	if errMsg_1 := retBuf.ReadString(); errMsg_1 != "" {
		err_1 = fmt.Errorf("%s", errMsg_1)
	}
	return v_0, err_1
}

func IOHostRouter(ctx context.Context, impl IO, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) ([]byte, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "ReadAll":
			methodID = MethodID_IO_ReadAll
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_IO_ReadAll:
		var r any
		rawVal := reqBuf.ReadAny()
		if id, ok := rawVal.(uint32); ok {
			if obj, ok := registry.Get(id); ok {
				r = obj
			} else {
				r = rawVal
			}
		} else {
			r = rawVal
		}
		r0, err := impl.ReadAll(r)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		resBuf.WriteString(ffigo.WrapError(err))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var IO_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
	Doc      string
}{
	{"ReadAll", 1, "function(Any) tuple(TypeBytes, String)", ""},
}

type IO_Bridge struct {
	Impl     IO
	Registry *ffigo.HandleRegistry
}

func (b *IO_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return IOHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *IO_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return IOHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *IO_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterIO(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType, string)
}, impl IO, registry *ffigo.HandleRegistry) {
	bridge := &IO_Bridge{Impl: impl, Registry: registry}
	prefix := "io"
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range IO_FFI_Metadata {
		executor.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec), m.Doc)
	}
}
