// Code generated by ffigen. DO NOT EDIT.
package iolib

import (
	"context"
	"fmt"
	"io"
)
import (
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

const (
	MethodID_IO_ReadAll     = 1
	MethodID_IO_Copy        = 2
	MethodID_IO_WriteString = 3
)

type IOProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewIOProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) IO {
	return &IOProxy{bridge: bridge, registry: registry}
}

func (__p *IOProxy) ReadAll(ctx context.Context, r any) ([]byte, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(r)

	retData, err := __p.bridge.Call(ctx, MethodID_IO_ReadAll, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *IOProxy) Copy(ctx context.Context, dst any, src any) (int64, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(dst)
	buf.WriteAny(src)

	retData, err := __p.bridge.Call(ctx, MethodID_IO_Copy, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *IOProxy) WriteString(ctx context.Context, w any, s string) (int64, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(w)
	buf.WriteString(string(s))

	retData, err := __p.bridge.Call(ctx, MethodID_IO_WriteString, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func IOHostRouter(ctx context.Context, impl IO, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "ReadAll":
			methodID = MethodID_IO_ReadAll
		case "Copy":
			methodID = MethodID_IO_Copy
		case "WriteString":
			methodID = MethodID_IO_WriteString
		}
	}

	reqBuf := ffigo.NewReader(args)
	var rawVal any
	_ = rawVal
	switch methodID {
	case MethodID_IO_ReadAll:
		var r any
		rawVal = reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, err := registry.GetWithAudit(rv); err == nil {
				r = obj
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "r", err)
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, err := registry.GetWithAudit(rv.Handle); err == nil {
					r = obj
				} else {
					return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "r", err)
				}
			} else {
				r = rv
			}
		default:
			r = rawVal
		}
		r0, err := impl.ReadAll(ctx, r)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_IO_Copy:
		var dst any
		rawVal = reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, err := registry.GetWithAudit(rv); err == nil {
				dst = obj
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "dst", err)
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, err := registry.GetWithAudit(rv.Handle); err == nil {
					dst = obj
				} else {
					return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "dst", err)
				}
			} else {
				dst = rv
			}
		default:
			dst = rawVal
		}
		var src any
		rawVal = reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, err := registry.GetWithAudit(rv); err == nil {
				src = obj
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "src", err)
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, err := registry.GetWithAudit(rv.Handle); err == nil {
					src = obj
				} else {
					return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "src", err)
				}
			} else {
				src = rv
			}
		default:
			src = rawVal
		}
		r0, err := impl.Copy(ctx, dst, src)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_IO_WriteString:
		var w any
		rawVal = reqBuf.ReadAny()
		switch rv := rawVal.(type) {
		case uint32:
			if obj, err := registry.GetWithAudit(rv); err == nil {
				w = obj
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "w", err)
			}
		case ffigo.ErrorData:
			if rv.Handle != 0 {
				if obj, err := registry.GetWithAudit(rv.Handle); err == nil {
					w = obj
				} else {
					return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "w", err)
				}
			} else {
				w = rv
			}
		default:
			w = rawVal
		}
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.WriteString(ctx, w, s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var IO_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"ReadAll", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Any) tuple(TypeBytes, Error)")), "ReadAll 读取所有数据"},
	{"Copy", 2, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Any, Any) tuple(Int64, Error)")), "Copy 将 src 的数据拷贝到 dst"},
	{"WriteString", 3, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Any, String) tuple(Int64, Error)")), "WriteString 将字符串写入 w"},
}

type IO_Bridge struct {
	Impl     IO
	Registry *ffigo.HandleRegistry
}

func (b *IO_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return IOHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *IO_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return IOHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *IO_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterIO(executor interface{ RegisterConstant(string, string) }, impl IO, registry *ffigo.HandleRegistry) {
	bridge := &IO_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registrar.RegisterFFISchema("io.ReadAll", bridge, IO_FFI_Schemas[0].MethodID, IO_FFI_Schemas[0].Sig, IO_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("io.Copy", bridge, IO_FFI_Schemas[1].MethodID, IO_FFI_Schemas[1].Sig, IO_FFI_Schemas[1].Doc)
	registrar.RegisterFFISchema("io.WriteString", bridge, IO_FFI_Schemas[2].MethodID, IO_FFI_Schemas[2].Sig, IO_FFI_Schemas[2].Doc)
	executor.RegisterConstant("io.SeekCurrent", ffigo.ToConstantString(io.SeekCurrent))
	executor.RegisterConstant("io.SeekEnd", ffigo.ToConstantString(io.SeekEnd))
	executor.RegisterConstant("io.SeekStart", ffigo.ToConstantString(io.SeekStart))
}

const (
	MethodID_File_Write       = 1
	MethodID_File_WriteAt     = 2
	MethodID_File_Seek        = 3
	MethodID_File_Close       = 4
	MethodID_File_Sync        = 5
	MethodID_File_Truncate    = 6
	MethodID_File_WriteString = 7
	MethodID_File_Name        = 8
	MethodID_File_WriteNative = 9
)

func FileHostRouter(ctx context.Context, impl *File, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Write":
			methodID = MethodID_File_Write
		case "WriteAt":
			methodID = MethodID_File_WriteAt
		case "Seek":
			methodID = MethodID_File_Seek
		case "Close":
			methodID = MethodID_File_Close
		case "Sync":
			methodID = MethodID_File_Sync
		case "Truncate":
			methodID = MethodID_File_Truncate
		case "WriteString":
			methodID = MethodID_File_WriteString
		case "Name":
			methodID = MethodID_File_Name
		case "WriteNative":
			methodID = MethodID_File_WriteNative
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_File_Write:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := __recv.Write(b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_WriteAt:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		var off int64
		{
			tmp := reqBuf.ReadVarint()
			off = int64(tmp)
		}
		r0, err := __recv.WriteAt(b, off)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_Seek:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var offset int64
		{
			tmp := reqBuf.ReadVarint()
			offset = int64(tmp)
		}
		var whence int
		{
			tmp := reqBuf.ReadVarint()
			whence = int(tmp)
		}
		r0, err := __recv.Seek(offset, whence)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_Close:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		err := __recv.Close()
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_Sync:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		err := __recv.Sync()
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_Truncate:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var size int64
		{
			tmp := reqBuf.ReadVarint()
			size = int64(tmp)
		}
		err := __recv.Truncate(size)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_WriteString:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var s string
		s = string(reqBuf.ReadString())
		r0, err := __recv.WriteString(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_File_Name:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Name()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_File_WriteNative:
		var __recv *File
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				__recv = obj.(*File)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var p []byte
		p = reqBuf.ReadBytes()
		r0, err := __recv.WriteNative(p)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var File_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Write", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>, TypeBytes) tuple(Int64, Error)")), "Write 正常工作：宿主读取脚本提供的 []byte 内容"},
	{"WriteAt", 2, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>, TypeBytes, Int64) tuple(Int64, Error)")), "WriteAt 正常工作：支持偏移量写入"},
	{"Seek", 3, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>, Int64, Int64) tuple(Int64, Error)")), ""},
	{"Close", 4, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>) Error")), ""},
	{"Sync", 5, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>) Error")), ""},
	{"Truncate", 6, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>, Int64) Error")), ""},
	{"WriteString", 7, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>, String) tuple(Int64, Error)")), ""},
	{"Name", 8, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>) String")), ""},
	{"WriteNative", 9, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<io.File>, TypeBytes) tuple(Int64, Error)")), "满足 io.Writer 接口，供宿主侧其他库使用"},
}

type File_Bridge struct {
	Impl     *File
	Registry *ffigo.HandleRegistry
}

func (b *File_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return FileHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *File_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return FileHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *File_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

var File_StructSchema = runtime.MustParseRuntimeStructSpec("io.File", ast.GoMiniType("struct { F Ptr<os.File>; Write function(Ptr<io.File>, TypeBytes) tuple(Int64, Error); WriteAt function(Ptr<io.File>, TypeBytes, Int64) tuple(Int64, Error); Seek function(Ptr<io.File>, Int64, Int64) tuple(Int64, Error); Close function(Ptr<io.File>) Error; Sync function(Ptr<io.File>) Error; Truncate function(Ptr<io.File>, Int64) Error; WriteString function(Ptr<io.File>, String) tuple(Int64, Error); Name function(Ptr<io.File>) String; WriteNative function(Ptr<io.File>, TypeBytes) tuple(Int64, Error); }"))

func RegisterFile(executor interface{ RegisterConstant(string, string) }, registry *ffigo.HandleRegistry) {
	bridge := &File_Bridge{Impl: nil, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		if checker, ok := executor.(interface{ HasStructSchema(string) bool }); ok && checker.HasStructSchema(name) {
			return
		}
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("io.File.Write", bridge, File_FFI_Schemas[0].MethodID, File_FFI_Schemas[0].Sig, File_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("io.File.WriteAt", bridge, File_FFI_Schemas[1].MethodID, File_FFI_Schemas[1].Sig, File_FFI_Schemas[1].Doc)
	registrar.RegisterFFISchema("io.File.Seek", bridge, File_FFI_Schemas[2].MethodID, File_FFI_Schemas[2].Sig, File_FFI_Schemas[2].Doc)
	registrar.RegisterFFISchema("io.File.Close", bridge, File_FFI_Schemas[3].MethodID, File_FFI_Schemas[3].Sig, File_FFI_Schemas[3].Doc)
	registrar.RegisterFFISchema("io.File.Sync", bridge, File_FFI_Schemas[4].MethodID, File_FFI_Schemas[4].Sig, File_FFI_Schemas[4].Doc)
	registrar.RegisterFFISchema("io.File.Truncate", bridge, File_FFI_Schemas[5].MethodID, File_FFI_Schemas[5].Sig, File_FFI_Schemas[5].Doc)
	registrar.RegisterFFISchema("io.File.WriteString", bridge, File_FFI_Schemas[6].MethodID, File_FFI_Schemas[6].Sig, File_FFI_Schemas[6].Doc)
	registrar.RegisterFFISchema("io.File.Name", bridge, File_FFI_Schemas[7].MethodID, File_FFI_Schemas[7].Sig, File_FFI_Schemas[7].Doc)
	registrar.RegisterFFISchema("io.File.WriteNative", bridge, File_FFI_Schemas[8].MethodID, File_FFI_Schemas[8].Sig, File_FFI_Schemas[8].Doc)
	registerStructSchema("io.File", File_StructSchema)
}
