// Code generated by ffigen. DO NOT EDIT.
package iolib

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_IO_ReadAll = 1
)

type IOProxy struct {
	bridge ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *IOProxy) ReadAll(ctx context.Context, r any) ([]byte, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteAny(r)

	retData, err := p.bridge.Call(ctx, MethodID_IO_ReadAll, buf.Bytes())
	_ = retData
	if err != nil { return nil, err }
	retBuf := ffigo.NewReader(retData)
	status := retBuf.ReadByte()
	if status != 0 {
		errMsg := retBuf.ReadString()
		return nil, fmt.Errorf("%s", errMsg)
	}
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	return v_0, nil
}

func IOHostRouter(ctx context.Context, impl IO, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	_ = reqBuf
	switch methodID {
	case MethodID_IO_ReadAll:
		var r any
		rawVal := reqBuf.ReadAny()
		if id, ok := rawVal.(uint32); ok {
			if obj, ok := registry.Get(id); ok {
				r = obj
			} else {
				r = rawVal
			}
		} else {
			r = rawVal
		}
		r0, err := impl.ReadAll(r)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			resBuf.WriteByte(1)
			resBuf.WriteString(err.Error())
		} else {
			resBuf.WriteByte(0)
	resBuf.WriteBytes(r0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}
