package doc

import (
	"bytes"
	"fmt"
	commentdoc "go/doc/comment"
	"net/url"
	"path"
	"sort"
	"strings"
	"unicode"
)

// Renderer owns the immutable indexes shared by full and per-symbol Markdown
// rendering.
type Renderer struct {
	catalog  Catalog
	packages map[string]Package
}

func NewRenderer(catalog Catalog) Renderer {
	packages := make(map[string]Package, len(catalog.Packages))
	for _, pkg := range catalog.Packages {
		packages[pkg.ModulePath] = pkg
	}
	return Renderer{catalog: catalog, packages: packages}
}

func Render(catalog Catalog) (Output, error) {
	return NewRenderer(catalog).Render()
}

func (r Renderer) Render() (Output, error) {
	var generated []Package
	for _, pkg := range r.catalog.Packages {
		if pkg.Generate {
			generated = append(generated, pkg)
		}
	}
	sort.Slice(generated, func(i, j int) bool { return generated[i].ModulePath < generated[j].ModulePath })
	output := Output{Files: []File{{Path: "README.md", Text: renderIndex(generated, r.catalog.Target.Tags)}}}
	seen := map[string]struct{}{"README.md": {}}
	for _, pkg := range generated {
		if err := validatePackageAnchors(pkg); err != nil {
			return Output{}, err
		}
		filePath, err := packageFilePath(pkg.ModulePath)
		if err != nil {
			return Output{}, err
		}
		folded := strings.ToLower(filePath)
		if _, exists := seen[folded]; exists {
			return Output{}, fmt.Errorf("documentation output path collision for %q", pkg.ModulePath)
		}
		seen[folded] = struct{}{}
		output.Files = append(output.Files, File{Path: filePath, Text: renderPackage(pkg, r.packages, filePath, r.catalog.Target.Tags)})
	}
	sort.Slice(output.Files, func(i, j int) bool { return output.Files[i].Path < output.Files[j].Path })
	return output, nil
}

func validatePackageAnchors(pkg Package) error {
	seen := map[string]string{}
	add := func(heading string) error {
		anchor := headingAnchor(heading)
		if anchor == "" {
			return fmt.Errorf("package %q has an empty Markdown anchor for %q", pkg.ModulePath, heading)
		}
		if previous := seen[anchor]; previous != "" {
			return fmt.Errorf("package %q has duplicate Markdown anchor %q for %q and %q", pkg.ModulePath, anchor, previous, heading)
		}
		seen[anchor] = heading
		return nil
	}
	for _, symbol := range publicSymbols(pkg.Symbols) {
		if err := add(symbolHeading(symbol)); err != nil {
			return err
		}
		if symbol.Kind != "type" {
			continue
		}
		for _, member := range symbol.Members {
			if member.Exported && member.Name != "" {
				if err := add(member.Kind + " " + symbol.Name + "." + member.Name); err != nil {
					return err
				}
			}
		}
		for _, method := range symbol.Methods {
			if method.Exported {
				if err := add(symbolHeading(method)); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// RenderComment renders one catalog comment using the same link rules as the
// generated package reference.
func RenderComment(catalog Catalog, modulePath string, source Comment) string {
	return NewRenderer(catalog).RenderComment(modulePath, source)
}

func (r Renderer) RenderComment(modulePath string, source Comment) string {
	pkg, exists := r.packages[modulePath]
	if !exists {
		return ""
	}
	filePath, err := packageFilePath(modulePath)
	if err != nil {
		return ""
	}
	var out bytes.Buffer
	writeComment(&out, source, pkg, r.packages, filePath)
	return strings.TrimSpace(out.String())
}

func renderIndex(packages []Package, tags []string) []byte {
	var out bytes.Buffer
	out.WriteString("<!-- Generated by mini-go doc. Target: ")
	out.WriteString(strings.Join(tags, ","))
	out.WriteString(". -->\n\n# Mini-Go package reference\n")
	if len(packages) != 0 {
		out.WriteString("\n## Packages\n\n")
	}
	for _, pkg := range packages {
		filePath, _ := packageFilePath(pkg.ModulePath)
		fmt.Fprintf(&out, "- [`%s`](%s)", pkg.ModulePath, filePath)
		if synopsis := commentSynopsis(pkg.Doc.Text); synopsis != "" {
			out.WriteString(" - ")
			out.WriteString(synopsis)
		}
		out.WriteByte('\n')
	}
	return finishMarkdown(out.Bytes())
}

func renderPackage(pkg Package, packages map[string]Package, filePath string, tags []string) []byte {
	var out bytes.Buffer
	fmt.Fprintf(&out, "<!-- Generated by mini-go doc. Target: %s. -->\n\n# Package `%s`\n\n", strings.Join(tags, ","), pkg.ModulePath)
	fmt.Fprintf(&out, "```go\npackage %s\n```\n", pkg.Name)
	writeComment(&out, pkg.Doc, pkg, packages, filePath)
	public := publicSymbols(pkg.Symbols)
	if len(public) != 0 {
		out.WriteString("\n## Index\n\n")
		for _, symbol := range public {
			fmt.Fprintf(&out, "- [%s %s](#%s)\n", symbol.Kind, symbol.Name, headingAnchor(symbolHeading(symbol)))
			for _, method := range symbol.Methods {
				if method.Exported {
					fmt.Fprintf(&out, "  - [%s.%s](#%s)\n", symbol.Name, method.Name, headingAnchor(symbolHeading(method)))
				}
			}
		}
	}
	for _, section := range []struct {
		title string
		kind  string
	}{{"Constants", "const"}, {"Variables", "var"}, {"Functions", "func"}, {"Types", "type"}} {
		var symbols []Symbol
		for _, symbol := range public {
			if symbol.Kind == section.kind {
				symbols = append(symbols, symbol)
			}
		}
		if len(symbols) == 0 {
			continue
		}
		fmt.Fprintf(&out, "\n## %s\n", section.title)
		writtenDocs := map[string]bool{}
		for _, symbol := range symbols {
			fmt.Fprintf(&out, "\n### %s\n\n```go\n%s\n```\n", symbolHeading(symbol), symbol.DisplaySignature)
			if symbol.Doc.Key == "" || !writtenDocs[symbol.Doc.Key] || section.kind == "type" {
				writeComment(&out, symbol.Doc, pkg, packages, filePath)
				writtenDocs[symbol.Doc.Key] = symbol.Doc.Key != ""
			}
			if symbol.Kind == "type" {
				writeMembers(&out, symbol, pkg, packages, filePath)
			}
		}
	}
	if len(pkg.Notes) != 0 {
		out.WriteString("\n## Notes\n")
		for _, note := range pkg.Notes {
			fmt.Fprintf(&out, "\n- **%s(%s):** %s\n", note.Marker, note.UID, note.Body)
		}
	}
	return finishMarkdown(out.Bytes())
}

func writeMembers(out *bytes.Buffer, owner Symbol, pkg Package, packages map[string]Package, filePath string) {
	for _, member := range owner.Members {
		if !member.Exported {
			continue
		}
		label := member.Kind + " " + owner.Name + "." + member.Name
		fmt.Fprintf(out, "\n#### %s\n\n```go\n%s\n```\n", label, member.Signature)
		writeComment(out, member.Doc, pkg, packages, filePath)
	}
	for _, method := range owner.Methods {
		if !method.Exported {
			continue
		}
		fmt.Fprintf(out, "\n#### %s\n\n```go\n%s\n```\n", symbolHeading(method), method.DisplaySignature)
		writeComment(out, method.Doc, pkg, packages, filePath)
	}
}

func writeComment(out *bytes.Buffer, source Comment, pkg Package, packages map[string]Package, filePath string) {
	if strings.TrimSpace(source.Text) == "" {
		return
	}
	symbols := map[string]bool{}
	for _, symbol := range pkg.Symbols {
		symbols[symbol.Name] = true
		for _, method := range symbol.Methods {
			symbols[symbol.Name+"."+method.Name] = true
		}
	}
	parser := commentdoc.Parser{
		LookupPackage: func(name string) (string, bool) {
			if name == pkg.Name {
				return "", true
			}
			modulePath, ok := pkg.Imports[name]
			return modulePath, ok
		},
		LookupSym: func(receiver, name string) bool {
			if receiver == "" {
				return symbols[name]
			}
			return symbols[receiver+"."+name]
		},
	}
	printer := commentdoc.Printer{
		HeadingLevel: 4,
		HeadingID:    func(*commentdoc.Heading) string { return "" },
		DocLinkURL: func(link *commentdoc.DocLink) string {
			targetPath := link.ImportPath
			if targetPath == "" {
				targetPath = pkg.ModulePath
			}
			target, ok := packages[targetPath]
			if !ok || !target.Generate {
				return ""
			}
			targetFile, err := packageFilePath(targetPath)
			if err != nil {
				return ""
			}
			url := relativeMarkdownPath(filePath, targetFile)
			if link.Name != "" {
				kind := symbolKind(target, link.Recv, link.Name)
				heading := kind + " " + link.Name
				if link.Recv != "" {
					heading = "func " + link.Recv + "." + link.Name
				}
				url += "#" + headingAnchor(heading)
			}
			return url
		},
	}
	parsed := parser.Parse(source.Text)
	sanitizeCommentLinks(parsed)
	rendered := bytes.TrimSpace(printer.Markdown(parsed))
	if len(rendered) != 0 {
		out.WriteByte('\n')
		out.Write(rendered)
		out.WriteByte('\n')
	}
}

func sanitizeCommentLinks(document *commentdoc.Doc) {
	var sanitizeText func([]commentdoc.Text) []commentdoc.Text
	sanitizeText = func(text []commentdoc.Text) []commentdoc.Text {
		out := make([]commentdoc.Text, 0, len(text))
		for _, item := range text {
			link, ok := item.(*commentdoc.Link)
			if !ok {
				out = append(out, item)
				continue
			}
			link.Text = sanitizeText(link.Text)
			if safeDocumentationURL(link.URL) {
				out = append(out, link)
			} else {
				out = append(out, link.Text...)
			}
		}
		return out
	}
	for _, block := range document.Content {
		switch block := block.(type) {
		case *commentdoc.Paragraph:
			block.Text = sanitizeText(block.Text)
		case *commentdoc.Heading:
			block.Text = sanitizeText(block.Text)
		case *commentdoc.List:
			for _, item := range block.Items {
				for _, content := range item.Content {
					if paragraph, ok := content.(*commentdoc.Paragraph); ok {
						paragraph.Text = sanitizeText(paragraph.Text)
					}
				}
			}
		}
	}
}

func safeDocumentationURL(text string) bool {
	text = strings.TrimSpace(text)
	parsed, err := url.Parse(text)
	if err != nil || strings.HasPrefix(text, "//") {
		return false
	}
	switch strings.ToLower(parsed.Scheme) {
	case "", "http", "https", "mailto":
		return true
	default:
		return false
	}
}

func publicSymbols(symbols []Symbol) []Symbol {
	out := make([]Symbol, 0, len(symbols))
	for _, symbol := range symbols {
		if symbol.Exported {
			out = append(out, symbol)
		}
	}
	return out
}

func symbolHeading(symbol Symbol) string {
	if symbol.Kind == "method" {
		return "func " + strings.TrimPrefix(symbol.Receiver, "*") + "." + symbol.Name
	}
	return symbol.Kind + " " + symbol.Name
}

func symbolKind(pkg Package, receiver, name string) string {
	if receiver != "" {
		return "func"
	}
	for _, symbol := range pkg.Symbols {
		if symbol.Name == name {
			return symbol.Kind
		}
	}
	return ""
}

func headingAnchor(heading string) string {
	var out strings.Builder
	space := false
	for _, r := range strings.ToLower(heading) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' || r == '-':
			if space && out.Len() != 0 {
				out.WriteByte('-')
			}
			space = false
			out.WriteRune(r)
		case unicode.IsSpace(r):
			space = true
		}
	}
	return strings.Trim(out.String(), "-")
}

func packageFilePath(modulePath string) (string, error) {
	cleaned := path.Clean(strings.TrimSpace(modulePath))
	if cleaned == "." || cleaned == "" || cleaned == ".." || strings.HasPrefix(cleaned, "../") || path.IsAbs(cleaned) {
		return "", fmt.Errorf("invalid documentation module path %q", modulePath)
	}
	return "packages/" + cleaned + ".md", nil
}

func relativeMarkdownPath(current, target string) string {
	currentDir := path.Dir(current)
	currentParts := strings.Split(strings.Trim(currentDir, "/"), "/")
	targetParts := strings.Split(strings.Trim(target, "/"), "/")
	common := 0
	for common < len(currentParts) && common < len(targetParts) && currentParts[common] == targetParts[common] {
		common++
	}
	return strings.Repeat("../", len(currentParts)-common) + strings.Join(targetParts[common:], "/")
}

func commentSynopsis(text string) string {
	text = strings.TrimSpace(strings.Split(text, "\n\n")[0])
	text = strings.Join(strings.Fields(text), " ")
	for i := 0; i+1 < len(text); i++ {
		if text[i] == '.' && text[i+1] == ' ' {
			return text[:i+1]
		}
	}
	return text
}

func finishMarkdown(data []byte) []byte {
	return append(bytes.TrimRight(data, " \t\r\n"), '\n')
}
