// Code generated by ffigen. DO NOT EDIT.
package strconvlib

import (
	"context"
	"fmt"
	"strconv"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	MethodID_Strconv_Atoi        = 1
	MethodID_Strconv_Itoa        = 2
	MethodID_Strconv_ParseBool   = 3
	MethodID_Strconv_ParseFloat  = 4
	MethodID_Strconv_ParseInt    = 5
	MethodID_Strconv_FormatBool  = 6
	MethodID_Strconv_FormatFloat = 7
	MethodID_Strconv_FormatInt   = 8
	MethodID_Strconv_Quote       = 9
	MethodID_Strconv_Unquote     = 10
)

type StrconvProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewStrconvProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) Strconv {
	return &StrconvProxy{bridge: bridge, registry: registry}
}

func (__p *StrconvProxy) Atoi(s string) (int, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(s))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_Atoi, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int
	{
		tmp := retBuf.ReadVarint()
		v_0 = int(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *StrconvProxy) Itoa(i int) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteVarint(int64(i))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_Itoa, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *StrconvProxy) ParseBool(str string) (bool, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(str))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_ParseBool, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return false, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 bool
	v_0 = bool(retBuf.ReadBool())
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *StrconvProxy) ParseFloat(s string, bitSize int) (float64, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(s))
	wireBuf.WriteVarint(int64(bitSize))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_ParseFloat, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return 0.0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *StrconvProxy) ParseInt(s string, base int, bitSize int) (int64, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(s))
	wireBuf.WriteVarint(int64(base))
	wireBuf.WriteVarint(int64(bitSize))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_ParseInt, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func (__p *StrconvProxy) FormatBool(b bool) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteBool(bool(b))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_FormatBool, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *StrconvProxy) FormatFloat(f float64, format uint8, prec int, bitSize int) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(f))
	wireBuf.WriteUvarint(uint64(format))
	wireBuf.WriteVarint(int64(prec))
	wireBuf.WriteVarint(int64(bitSize))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_FormatFloat, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *StrconvProxy) FormatInt(i int64, base int) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteVarint(int64(i))
	wireBuf.WriteVarint(int64(base))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_FormatInt, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *StrconvProxy) Quote(s string) string {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(s))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_Quote, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func (__p *StrconvProxy) Unquote(s string) (string, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(s))

	__ret, err := __p.bridge.Call(context.Background(), &ffigo.FFICallRequest{MethodID: MethodID_Strconv_Unquote, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return "", err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	var err_1 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = ed
				}
			} else {
				err_1 = ed
			}
		}
	}
	return v_0, err_1
}

func StrconvHostRouter(ctx context.Context, impl Strconv, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Atoi":
			methodID = MethodID_Strconv_Atoi
		case "Itoa":
			methodID = MethodID_Strconv_Itoa
		case "ParseBool":
			methodID = MethodID_Strconv_ParseBool
		case "ParseFloat":
			methodID = MethodID_Strconv_ParseFloat
		case "ParseInt":
			methodID = MethodID_Strconv_ParseInt
		case "FormatBool":
			methodID = MethodID_Strconv_FormatBool
		case "FormatFloat":
			methodID = MethodID_Strconv_FormatFloat
		case "FormatInt":
			methodID = MethodID_Strconv_FormatInt
		case "Quote":
			methodID = MethodID_Strconv_Quote
		case "Unquote":
			methodID = MethodID_Strconv_Unquote
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Strconv_Atoi:
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.Atoi(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Strconv_Itoa:
		var i int
		{
			tmp := reqBuf.ReadVarint()
			i = int(tmp)
		}
		r0 := impl.Itoa(i)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_Strconv_ParseBool:
		var str string
		str = string(reqBuf.ReadString())
		r0, err := impl.ParseBool(str)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Strconv_ParseFloat:
		var s string
		s = string(reqBuf.ReadString())
		var bitSize int
		{
			tmp := reqBuf.ReadVarint()
			bitSize = int(tmp)
		}
		r0, err := impl.ParseFloat(s, bitSize)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Strconv_ParseInt:
		var s string
		s = string(reqBuf.ReadString())
		var base int
		{
			tmp := reqBuf.ReadVarint()
			base = int(tmp)
		}
		var bitSize int
		{
			tmp := reqBuf.ReadVarint()
			bitSize = int(tmp)
		}
		r0, err := impl.ParseInt(s, base, bitSize)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Strconv_FormatBool:
		var b bool
		b = bool(reqBuf.ReadBool())
		r0 := impl.FormatBool(b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_Strconv_FormatFloat:
		var f float64
		f = float64(reqBuf.ReadFloat64())
		var format uint8
		{
			tmp := reqBuf.ReadVarint()
			if tmp < 0 || tmp > 255 {
				panic(fmt.Sprintf("ffi: uint8 overflow: %d", tmp))
			}
			format = uint8(tmp)
		}
		var prec int
		{
			tmp := reqBuf.ReadVarint()
			prec = int(tmp)
		}
		var bitSize int
		{
			tmp := reqBuf.ReadVarint()
			bitSize = int(tmp)
		}
		r0 := impl.FormatFloat(f, format, prec, bitSize)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_Strconv_FormatInt:
		var i int64
		{
			tmp := reqBuf.ReadVarint()
			i = int64(tmp)
		}
		var base int
		{
			tmp := reqBuf.ReadVarint()
			base = int(tmp)
		}
		r0 := impl.FormatInt(i, base)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_Strconv_Quote:
		var s string
		s = string(reqBuf.ReadString())
		r0 := impl.Quote(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case MethodID_Strconv_Unquote:
		var s string
		s = string(reqBuf.ReadString())
		r0, err := impl.Unquote(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Strconv_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Atoi", 1, runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(Int64, Error)", runtime.FFIParamIn), ""},
	{"Itoa", 2, runtime.MustParseRuntimeFuncSigWithModes("function(Int64) String", runtime.FFIParamIn), ""},
	{"ParseBool", 3, runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(Bool, Error)", runtime.FFIParamIn), ""},
	{"ParseFloat", 4, runtime.MustParseRuntimeFuncSigWithModes("function(String, Int64) tuple(Float64, Error)", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"ParseInt", 5, runtime.MustParseRuntimeFuncSigWithModes("function(String, Int64, Int64) tuple(Int64, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"FormatBool", 6, runtime.MustParseRuntimeFuncSigWithModes("function(Bool) String", runtime.FFIParamIn), ""},
	{"FormatFloat", 7, runtime.MustParseRuntimeFuncSigWithModes("function(Float64, Int64, Int64, Int64) String", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"FormatInt", 8, runtime.MustParseRuntimeFuncSigWithModes("function(Int64, Int64) String", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Quote", 9, runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), ""},
	{"Unquote", 10, runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(String, Error)", runtime.FFIParamIn), ""},
}

type Strconv_Bridge struct {
	Impl     Strconv
	Registry *ffigo.HandleRegistry
}

func (b *Strconv_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return StrconvHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Strconv_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return StrconvHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Strconv_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceStrconv(impl Strconv) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddFunc("strconv", "Atoi", "strconv.Atoi", Strconv_FFI_Schemas[0].MethodID, Strconv_FFI_Schemas[0].Sig, Strconv_FFI_Schemas[0].Doc)
	schema.AddFunc("strconv", "Itoa", "strconv.Itoa", Strconv_FFI_Schemas[1].MethodID, Strconv_FFI_Schemas[1].Sig, Strconv_FFI_Schemas[1].Doc)
	schema.AddFunc("strconv", "ParseBool", "strconv.ParseBool", Strconv_FFI_Schemas[2].MethodID, Strconv_FFI_Schemas[2].Sig, Strconv_FFI_Schemas[2].Doc)
	schema.AddFunc("strconv", "ParseFloat", "strconv.ParseFloat", Strconv_FFI_Schemas[3].MethodID, Strconv_FFI_Schemas[3].Sig, Strconv_FFI_Schemas[3].Doc)
	schema.AddFunc("strconv", "ParseInt", "strconv.ParseInt", Strconv_FFI_Schemas[4].MethodID, Strconv_FFI_Schemas[4].Sig, Strconv_FFI_Schemas[4].Doc)
	schema.AddFunc("strconv", "FormatBool", "strconv.FormatBool", Strconv_FFI_Schemas[5].MethodID, Strconv_FFI_Schemas[5].Sig, Strconv_FFI_Schemas[5].Doc)
	schema.AddFunc("strconv", "FormatFloat", "strconv.FormatFloat", Strconv_FFI_Schemas[6].MethodID, Strconv_FFI_Schemas[6].Sig, Strconv_FFI_Schemas[6].Doc)
	schema.AddFunc("strconv", "FormatInt", "strconv.FormatInt", Strconv_FFI_Schemas[7].MethodID, Strconv_FFI_Schemas[7].Sig, Strconv_FFI_Schemas[7].Doc)
	schema.AddFunc("strconv", "Quote", "strconv.Quote", Strconv_FFI_Schemas[8].MethodID, Strconv_FFI_Schemas[8].Sig, Strconv_FFI_Schemas[8].Doc)
	schema.AddFunc("strconv", "Unquote", "strconv.Unquote", Strconv_FFI_Schemas[9].MethodID, Strconv_FFI_Schemas[9].Sig, Strconv_FFI_Schemas[9].Doc)
	schema.AddConst("strconv", "IntSize", ffigo.ToConstantString(strconv.IntSize))
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &Strconv_Bridge{Impl: impl, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.AddRoute("strconv", "Atoi", runtime.FFIRoute{Name: "strconv.Atoi", Bridge: bridge, MethodID: Strconv_FFI_Schemas[0].MethodID, FuncSig: Strconv_FFI_Schemas[0].Sig, Doc: Strconv_FFI_Schemas[0].Doc})
		bound.AddRoute("strconv", "Itoa", runtime.FFIRoute{Name: "strconv.Itoa", Bridge: bridge, MethodID: Strconv_FFI_Schemas[1].MethodID, FuncSig: Strconv_FFI_Schemas[1].Sig, Doc: Strconv_FFI_Schemas[1].Doc})
		bound.AddRoute("strconv", "ParseBool", runtime.FFIRoute{Name: "strconv.ParseBool", Bridge: bridge, MethodID: Strconv_FFI_Schemas[2].MethodID, FuncSig: Strconv_FFI_Schemas[2].Sig, Doc: Strconv_FFI_Schemas[2].Doc})
		bound.AddRoute("strconv", "ParseFloat", runtime.FFIRoute{Name: "strconv.ParseFloat", Bridge: bridge, MethodID: Strconv_FFI_Schemas[3].MethodID, FuncSig: Strconv_FFI_Schemas[3].Sig, Doc: Strconv_FFI_Schemas[3].Doc})
		bound.AddRoute("strconv", "ParseInt", runtime.FFIRoute{Name: "strconv.ParseInt", Bridge: bridge, MethodID: Strconv_FFI_Schemas[4].MethodID, FuncSig: Strconv_FFI_Schemas[4].Sig, Doc: Strconv_FFI_Schemas[4].Doc})
		bound.AddRoute("strconv", "FormatBool", runtime.FFIRoute{Name: "strconv.FormatBool", Bridge: bridge, MethodID: Strconv_FFI_Schemas[5].MethodID, FuncSig: Strconv_FFI_Schemas[5].Sig, Doc: Strconv_FFI_Schemas[5].Doc})
		bound.AddRoute("strconv", "FormatFloat", runtime.FFIRoute{Name: "strconv.FormatFloat", Bridge: bridge, MethodID: Strconv_FFI_Schemas[6].MethodID, FuncSig: Strconv_FFI_Schemas[6].Sig, Doc: Strconv_FFI_Schemas[6].Doc})
		bound.AddRoute("strconv", "FormatInt", runtime.FFIRoute{Name: "strconv.FormatInt", Bridge: bridge, MethodID: Strconv_FFI_Schemas[7].MethodID, FuncSig: Strconv_FFI_Schemas[7].Sig, Doc: Strconv_FFI_Schemas[7].Doc})
		bound.AddRoute("strconv", "Quote", runtime.FFIRoute{Name: "strconv.Quote", Bridge: bridge, MethodID: Strconv_FFI_Schemas[8].MethodID, FuncSig: Strconv_FFI_Schemas[8].Sig, Doc: Strconv_FFI_Schemas[8].Doc})
		bound.AddRoute("strconv", "Unquote", runtime.FFIRoute{Name: "strconv.Unquote", Bridge: bridge, MethodID: Strconv_FFI_Schemas[9].MethodID, FuncSig: Strconv_FFI_Schemas[9].Sig, Doc: Strconv_FFI_Schemas[9].Doc})
		bound.AddConst("strconv", "IntSize", ffigo.ToConstantString(strconv.IntSize))
		return bound, nil
	})
}
