// Code generated by ffigen. DO NOT EDIT.
package fmtlib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDFmtPrint   = 1
	methodIDFmtPrintln = 2
	methodIDFmtPrintf  = 3
	methodIDFmtSprintf = 4
)

func fmtHostRouter(ctx context.Context, impl Fmt, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Print":
			methodID = methodIDFmtPrint
		case "Println":
			methodID = methodIDFmtPrintln
		case "Printf":
			methodID = methodIDFmtPrintf
		case "Sprintf":
			methodID = methodIDFmtSprintf
		}
	}

	reqBuf := ffigo.NewReader(args)
	var rawVal any
	_ = rawVal
	switch methodID {
	case methodIDFmtPrint:
		var args []any
		l_args, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "array")
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal, _ = reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case ffigo.InterfaceData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host interface handle", "args[i_args]")
				}
				args[i_args] = rv
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host error handle", "args[i_args]")
				}
				args[i_args] = rv
			default:
				args[i_args] = rawVal
			}
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Fmt.Print failed: %w", err)
		}
		impl.Print(ctx, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case methodIDFmtPrintln:
		var args []any
		l_args, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "array")
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal, _ = reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case ffigo.InterfaceData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host interface handle", "args[i_args]")
				}
				args[i_args] = rv
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host error handle", "args[i_args]")
				}
				args[i_args] = rv
			default:
				args[i_args] = rawVal
			}
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Fmt.Println failed: %w", err)
		}
		impl.Println(ctx, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case methodIDFmtPrintf:
		var format string
		{
			tmp, _ := reqBuf.ReadString()
			format = string(tmp)
		}
		var args []any
		l_args, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "array")
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal, _ = reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case ffigo.InterfaceData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host interface handle", "args[i_args]")
				}
				args[i_args] = rv
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host error handle", "args[i_args]")
				}
				args[i_args] = rv
			default:
				args[i_args] = rawVal
			}
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Fmt.Printf failed: %w", err)
		}
		impl.Printf(ctx, format, args...)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case methodIDFmtSprintf:
		var format string
		{
			tmp, _ := reqBuf.ReadString()
			format = string(tmp)
		}
		var args []any
		l_args, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "array")
		args = make([]any, l_args)
		for i_args := 0; i_args < l_args; i_args++ {
			rawVal, _ = reqBuf.ReadAny()
			switch rv := rawVal.(type) {
			case ffigo.InterfaceData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host interface handle", "args[i_args]")
				}
				args[i_args] = rv
			case ffigo.ErrorData:
				if rv.Handle != 0 {
					return nil, fmt.Errorf("FFI Any param '%s' cannot carry host error handle", "args[i_args]")
				}
				args[i_args] = rv
			default:
				args[i_args] = rawVal
			}
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Fmt.Sprintf failed: %w", err)
		}
		r0 := impl.Sprintf(ctx, format, args...)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var fmtRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "fmt", MemberName: "Print", RouteName: "fmt.Print", MethodID: methodIDFmtPrint, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(...Any) Void", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "fmt", MemberName: "Println", RouteName: "fmt.Println", MethodID: methodIDFmtPrintln, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(...Any) Void", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "fmt", MemberName: "Printf", RouteName: "fmt.Printf", MethodID: methodIDFmtPrintf, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, ...Any) Void", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
	{PackagePath: "fmt", MemberName: "Sprintf", RouteName: "fmt.Sprintf", MethodID: methodIDFmtSprintf, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, ...Any) String", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
}

func SurfaceFmt(impl Fmt) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	if err := schema.AddRouteDecls(fmtRoutes); err != nil {
		panic(err)
	}
	if err := schema.AddConst("fmt", "FMTKey", runtime.ConstString(string("gomini.fmt.Outputter"))); err != nil {
		panic(err)
	}
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return fmtHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
