// Code generated by ffigen. DO NOT EDIT.
package hexlib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDHexEncodeToString = 1
	methodIDHexDecodeString   = 2
	methodIDHexDump           = 3
)

func hexHostRouter(ctx context.Context, impl Hex, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "EncodeToString":
			methodID = methodIDHexEncodeToString
		case "DecodeString":
			methodID = methodIDHexDecodeString
		case "Dump":
			methodID = methodIDHexDump
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDHexEncodeToString:
		var src []byte
		src, _ = reqBuf.ReadBytes()
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Hex.EncodeToString failed: %w", err)
		}
		r0 := impl.EncodeToString(src)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDHexDecodeString:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Hex.DecodeString failed: %w", err)
		}
		r0, err := impl.DecodeString(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDHexDump:
		var data []byte
		data, _ = reqBuf.ReadBytes()
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for Hex.Dump failed: %w", err)
		}
		r0 := impl.Dump(data)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var hexRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "encoding/hex", MemberName: "EncodeToString", RouteName: "encoding/hex.EncodeToString", MethodID: methodIDHexEncodeToString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Array<Byte>) String", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "encoding/hex", MemberName: "DecodeString", RouteName: "encoding/hex.DecodeString", MethodID: methodIDHexDecodeString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(Array<Byte>, Error)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "encoding/hex", MemberName: "Dump", RouteName: "encoding/hex.Dump", MethodID: methodIDHexDump, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Array<Byte>) String", runtime.FFIParamIn), Doc: ""},
}

func SurfaceHex(impl Hex) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	if err := schema.AddRouteDecls(hexRoutes); err != nil {
		return &surface.Bundle{Err: err}
	}
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return hexHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
