package main

import (
	"errors"
	"flag"
	"io"
	"strings"

	"github.com/d7z-team/mini-go/runtime/bytecode"
)

func runContractSpec(args []string, stderr io.Writer) error {
	flags := flag.NewFlagSet("mini-go-dev contract-spec", flag.ContinueOnError)
	flags.SetOutput(stderr)
	output := flags.String("out", "", "generated bytecode contract")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 || strings.TrimSpace(*output) == "" {
		return errors.New("contract-spec requires -out")
	}
	data, err := bytecode.EncodeSpecJSON()
	if err != nil {
		return err
	}
	return writeGeneratedFile(*output, data)
}
