// Code generated by ffigen. DO NOT EDIT.
package urllib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDURLQueryEscape   = 1
	methodIDURLQueryUnescape = 2
	methodIDURLJoinPath      = 3
)

func urlHostRouter(ctx context.Context, impl URL, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "QueryEscape":
			methodID = methodIDURLQueryEscape
		case "QueryUnescape":
			methodID = methodIDURLQueryUnescape
		case "JoinPath":
			methodID = methodIDURLJoinPath
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDURLQueryEscape:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for URL.QueryEscape failed: %w", err)
		}
		r0 := impl.QueryEscape(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	case methodIDURLQueryUnescape:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for URL.QueryUnescape failed: %w", err)
		}
		r0, err := impl.QueryUnescape(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDURLJoinPath:
		var base string
		{
			tmp, _ := reqBuf.ReadString()
			base = string(tmp)
		}
		var elem []string
		l_elem, _ := reqBuf.ReadCount(ffigo.MaxWireCollectionItems, "array")
		elem = make([]string, l_elem)
		for i_elem := 0; i_elem < l_elem; i_elem++ {
			{
				tmp, _ := reqBuf.ReadString()
				elem[i_elem] = string(tmp)
			}
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for URL.JoinPath failed: %w", err)
		}
		r0 := impl.JoinPath(base, elem...)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var urlRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "net/url", MemberName: "QueryEscape", RouteName: "net/url.QueryEscape", MethodID: methodIDURLQueryEscape, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) String", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "net/url", MemberName: "QueryUnescape", RouteName: "net/url.QueryUnescape", MethodID: methodIDURLQueryUnescape, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(String, Error)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "net/url", MemberName: "JoinPath", RouteName: "net/url.JoinPath", MethodID: methodIDURLJoinPath, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String, ...String) String", runtime.FFIParamIn, runtime.FFIParamIn), Doc: ""},
}

func SurfaceURL(impl URL) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(urlRoutes)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return urlHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
