// Code generated by ffigen. DO NOT EDIT.
package canonicaltest

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ast"
	a_other "gopkg.d7z.net/go-mini/core/e2e/canonicaltest/internal/a/other"
	b_other "gopkg.d7z.net/go-mini/core/e2e/canonicaltest/internal/b/other"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

var a_other_Type_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("a_other.Type", ast.GoMiniType("struct { Hello function(Ptr<a_other.Type>) String; }"))

var b_other_Type_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("b_other.Type", ast.GoMiniType("struct { Hello function(Ptr<b_other.Type>) String; }"))

const (
	MethodID_TestCanonicalService_NewA = 1
	MethodID_TestCanonicalService_NewB = 2
)

type TestCanonicalServiceProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewTestCanonicalServiceProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) TestCanonicalService {
	return &TestCanonicalServiceProxy{bridge: bridge, registry: registry}
}

func (__p *TestCanonicalServiceProxy) NewA(ctx context.Context, name string) *a_other.Type {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(string(name))

	retData, err := __p.bridge.Call(ctx, MethodID_TestCanonicalService_NewA, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 *a_other.Type
	// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.Get(id); ok {
				v_0 = obj.(*a_other.Type)
			}
		}
	}
	return v_0
}

func (__p *TestCanonicalServiceProxy) NewB(ctx context.Context, id int) *b_other.Type {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteVarint(int64(id))

	retData, err := __p.bridge.Call(ctx, MethodID_TestCanonicalService_NewB, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 *b_other.Type
	// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.Get(id); ok {
				v_0 = obj.(*b_other.Type)
			}
		}
	}
	return v_0
}

func TestCanonicalServiceHostRouter(ctx context.Context, impl TestCanonicalService, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "NewA":
			methodID = MethodID_TestCanonicalService_NewA
		case "NewB":
			methodID = MethodID_TestCanonicalService_NewB
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_TestCanonicalService_NewA:
		var name string
		name = string(reqBuf.ReadString())
		r0 := impl.NewA(ctx, name)
		resBuf := ffigo.GetBuffer()
		// Ptr<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.Register(r0)))
		}
		return resBuf.Bytes(), nil
	case MethodID_TestCanonicalService_NewB:
		var id int
		{
			tmp := reqBuf.ReadVarint()
			id = int(tmp)
		}
		r0 := impl.NewB(ctx, id)
		resBuf := ffigo.GetBuffer()
		// Ptr<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.Register(r0)))
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var TestCanonicalService_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"NewA", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(String) Ptr<a_other.Type>")), ""},
	{"NewB", 2, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Int64) Ptr<b_other.Type>")), ""},
}

type TestCanonicalService_Bridge struct {
	Impl     TestCanonicalService
	Registry *ffigo.HandleRegistry
}

func (b *TestCanonicalService_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return TestCanonicalServiceHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *TestCanonicalService_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return TestCanonicalServiceHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *TestCanonicalService_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterTestCanonicalService(executor interface{ RegisterConstant(string, string) }, impl TestCanonicalService, registry *ffigo.HandleRegistry) {
	bridge := &TestCanonicalService_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registrar.RegisterFFISchema("test_canonical.NewA", bridge, TestCanonicalService_FFI_Schemas[0].MethodID, TestCanonicalService_FFI_Schemas[0].Sig, TestCanonicalService_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("test_canonical.NewB", bridge, TestCanonicalService_FFI_Schemas[1].MethodID, TestCanonicalService_FFI_Schemas[1].Sig, TestCanonicalService_FFI_Schemas[1].Doc)
}

const (
	MethodID_ATypeService_Hello = 1
)

type ATypeServiceProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewATypeServiceProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) ATypeService {
	return &ATypeServiceProxy{bridge: bridge, registry: registry}
}

func (__p *ATypeServiceProxy) Hello(t *a_other.Type) string {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	// Ptr<T> crosses the FFI boundary as an opaque handle ID.
	if t == nil {
		buf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			buf.WriteUvarint(uint64(__p.registry.Register(t)))
		} else {
			buf.WriteUvarint(0)
		}
	}

	retData, err := __p.bridge.Call(context.Background(), MethodID_ATypeService_Hello, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func ATypeServiceHostRouter(ctx context.Context, impl ATypeService, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Hello":
			methodID = MethodID_ATypeService_Hello
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_ATypeService_Hello:
		var t *a_other.Type
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				t = obj.(*a_other.Type)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "t", err)
			}
		}
		r0 := impl.Hello(t)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var ATypeService_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Hello", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<a_other.Type>) String")), ""},
}

type ATypeService_Bridge struct {
	Impl     ATypeService
	Registry *ffigo.HandleRegistry
}

func (b *ATypeService_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return ATypeServiceHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *ATypeService_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return ATypeServiceHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *ATypeService_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterATypeService(executor interface{ RegisterConstant(string, string) }, impl ATypeService, registry *ffigo.HandleRegistry) {
	bridge := &ATypeService_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		if checker, ok := executor.(interface{ HasStructSchema(string) bool }); ok && checker.HasStructSchema(name) {
			return
		}
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("a_other.Type.Hello", bridge, ATypeService_FFI_Schemas[0].MethodID, ATypeService_FFI_Schemas[0].Sig, ATypeService_FFI_Schemas[0].Doc)
	registerStructSchema("a_other.Type", a_other_Type_FFI_StructSchema)
}

const (
	MethodID_BTypeService_Hello = 1
)

type BTypeServiceProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewBTypeServiceProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) BTypeService {
	return &BTypeServiceProxy{bridge: bridge, registry: registry}
}

func (__p *BTypeServiceProxy) Hello(t *b_other.Type) string {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	// Ptr<T> crosses the FFI boundary as an opaque handle ID.
	if t == nil {
		buf.WriteUvarint(0)
	} else {
		if __p.registry != nil {
			buf.WriteUvarint(uint64(__p.registry.Register(t)))
		} else {
			buf.WriteUvarint(0)
		}
	}

	retData, err := __p.bridge.Call(context.Background(), MethodID_BTypeService_Hello, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = string(retBuf.ReadString())
	return v_0
}

func BTypeServiceHostRouter(ctx context.Context, impl BTypeService, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Hello":
			methodID = MethodID_BTypeService_Hello
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_BTypeService_Hello:
		var t *b_other.Type
		// Ptr<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetWithAudit(id); err == nil {
				t = obj.(*b_other.Type)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "t", err)
			}
		}
		r0 := impl.Hello(t)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var BTypeService_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Hello", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Ptr<b_other.Type>) String")), ""},
}

type BTypeService_Bridge struct {
	Impl     BTypeService
	Registry *ffigo.HandleRegistry
}

func (b *BTypeService_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return BTypeServiceHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *BTypeService_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return BTypeServiceHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *BTypeService_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterBTypeService(executor interface{ RegisterConstant(string, string) }, impl BTypeService, registry *ffigo.HandleRegistry) {
	bridge := &BTypeService_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registerStructSchema := func(name string, spec *runtime.RuntimeStructSpec) {
		if checker, ok := executor.(interface{ HasStructSchema(string) bool }); ok && checker.HasStructSchema(name) {
			return
		}
		registrar.RegisterStructSchema(name, spec)
	}
	registrar.RegisterFFISchema("b_other.Type.Hello", bridge, BTypeService_FFI_Schemas[0].MethodID, BTypeService_FFI_Schemas[0].Sig, BTypeService_FFI_Schemas[0].Doc)
	registerStructSchema("b_other.Type", b_other_Type_FFI_StructSchema)
}
