// Code generated by ffigen. DO NOT EDIT.
package utf8lib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

const (
	methodIDUTF8DecodeRuneInString = 1
	methodIDUTF8EncodeRune         = 2
	methodIDUTF8FullRuneInString   = 3
	methodIDUTF8RuneCountInString  = 4
	methodIDUTF8RuneLen            = 5
	methodIDUTF8ValidString        = 6
)

func utf8HostRouter(ctx context.Context, impl UTF8, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "DecodeRuneInString":
			methodID = methodIDUTF8DecodeRuneInString
		case "EncodeRune":
			methodID = methodIDUTF8EncodeRune
		case "FullRuneInString":
			methodID = methodIDUTF8FullRuneInString
		case "RuneCountInString":
			methodID = methodIDUTF8RuneCountInString
		case "RuneLen":
			methodID = methodIDUTF8RuneLen
		case "ValidString":
			methodID = methodIDUTF8ValidString
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDUTF8DecodeRuneInString:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for UTF8.DecodeRuneInString failed: %w", err)
		}
		r0, r1 := impl.DecodeRuneInString(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		resBuf.WriteVarint(int64(r1))
		return resBuf.Bytes(), nil
	case methodIDUTF8EncodeRune:
		var r int64
		{
			tmp, _ := reqBuf.ReadVarint()
			r = int64(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for UTF8.EncodeRune failed: %w", err)
		}
		r0 := impl.EncodeRune(r)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		return resBuf.Bytes(), nil
	case methodIDUTF8FullRuneInString:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for UTF8.FullRuneInString failed: %w", err)
		}
		r0 := impl.FullRuneInString(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	case methodIDUTF8RuneCountInString:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for UTF8.RuneCountInString failed: %w", err)
		}
		r0 := impl.RuneCountInString(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDUTF8RuneLen:
		var r int64
		{
			tmp, _ := reqBuf.ReadVarint()
			r = int64(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for UTF8.RuneLen failed: %w", err)
		}
		r0 := impl.RuneLen(r)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case methodIDUTF8ValidString:
		var s string
		{
			tmp, _ := reqBuf.ReadString()
			s = string(tmp)
		}
		if err := reqBuf.Err(); err != nil {
			return nil, fmt.Errorf("FFI decode params for UTF8.ValidString failed: %w", err)
		}
		r0 := impl.ValidString(s)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var utf8Routes = []runtime.FFIRouteDecl{
	{PackagePath: "unicode/utf8", MemberName: "DecodeRuneInString", RouteName: "unicode/utf8.DecodeRuneInString", MethodID: methodIDUTF8DecodeRuneInString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(Int64, Int64)", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "unicode/utf8", MemberName: "EncodeRune", RouteName: "unicode/utf8.EncodeRune", MethodID: methodIDUTF8EncodeRune, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Int64) Array<Byte>", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "unicode/utf8", MemberName: "FullRuneInString", RouteName: "unicode/utf8.FullRuneInString", MethodID: methodIDUTF8FullRuneInString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) Bool", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "unicode/utf8", MemberName: "RuneCountInString", RouteName: "unicode/utf8.RuneCountInString", MethodID: methodIDUTF8RuneCountInString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) Int64", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "unicode/utf8", MemberName: "RuneLen", RouteName: "unicode/utf8.RuneLen", MethodID: methodIDUTF8RuneLen, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(Int64) Int64", runtime.FFIParamIn), Doc: ""},
	{PackagePath: "unicode/utf8", MemberName: "ValidString", RouteName: "unicode/utf8.ValidString", MethodID: methodIDUTF8ValidString, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) Bool", runtime.FFIParamIn), Doc: ""},
}

func SurfaceUTF8(impl UTF8) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	if err := schema.AddRouteDecls(utf8Routes); err != nil {
		panic(err)
	}
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return utf8HostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
