// Code generated by ffigen. DO NOT EDIT.
package mathlib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

const (
	MethodID_Math_Abs   = 1
	MethodID_Math_Ceil  = 2
	MethodID_Math_Floor = 3
	MethodID_Math_Round = 4
	MethodID_Math_Sqrt  = 5
	MethodID_Math_Pow   = 6
	MethodID_Math_Min   = 7
	MethodID_Math_Max   = 8
	MethodID_Math_Sin   = 9
	MethodID_Math_Cos   = 10
	MethodID_Math_Tan   = 11
	MethodID_Math_Exp   = 12
	MethodID_Math_Log   = 13
	MethodID_Math_Log10 = 14
	MethodID_Math_NaN   = 15
	MethodID_Math_IsNaN = 16
	MethodID_Math_Inf   = 17
	MethodID_Math_IsInf = 18
)

type MathProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewMathProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) Math {
	return &MathProxy{bridge: bridge, registry: registry}
}

func (__p *MathProxy) Abs(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Abs, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Ceil(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Ceil, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Floor(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Floor, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Round(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Round, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Sqrt(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Sqrt, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Pow(x float64, y float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))
	wireBuf.WriteFloat64(float64(y))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Pow, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Min(x float64, y float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))
	wireBuf.WriteFloat64(float64(y))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Min, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Max(x float64, y float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))
	wireBuf.WriteFloat64(float64(y))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Max, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Sin(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Sin, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Cos(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Cos, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Tan(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Tan, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Exp(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Exp, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Log(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Log, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) Log10(x float64) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(x))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Log10, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) NaN() float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_NaN, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) IsNaN(f float64) bool {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(f))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_IsNaN, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 bool
	v_0 = bool(retBuf.ReadBool())
	return v_0
}

func (__p *MathProxy) Inf(sign int) float64 {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteVarint(int64(sign))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_Inf, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 float64
	v_0 = float64(retBuf.ReadFloat64())
	return v_0
}

func (__p *MathProxy) IsInf(f float64, sign int) bool {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteFloat64(float64(f))
	wireBuf.WriteVarint(int64(sign))

	retData, err := __p.bridge.Call(context.Background(), MethodID_Math_IsInf, wireBuf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 bool
	v_0 = bool(retBuf.ReadBool())
	return v_0
}

func MathHostRouter(ctx context.Context, impl Math, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Abs":
			methodID = MethodID_Math_Abs
		case "Ceil":
			methodID = MethodID_Math_Ceil
		case "Floor":
			methodID = MethodID_Math_Floor
		case "Round":
			methodID = MethodID_Math_Round
		case "Sqrt":
			methodID = MethodID_Math_Sqrt
		case "Pow":
			methodID = MethodID_Math_Pow
		case "Min":
			methodID = MethodID_Math_Min
		case "Max":
			methodID = MethodID_Math_Max
		case "Sin":
			methodID = MethodID_Math_Sin
		case "Cos":
			methodID = MethodID_Math_Cos
		case "Tan":
			methodID = MethodID_Math_Tan
		case "Exp":
			methodID = MethodID_Math_Exp
		case "Log":
			methodID = MethodID_Math_Log
		case "Log10":
			methodID = MethodID_Math_Log10
		case "NaN":
			methodID = MethodID_Math_NaN
		case "IsNaN":
			methodID = MethodID_Math_IsNaN
		case "Inf":
			methodID = MethodID_Math_Inf
		case "IsInf":
			methodID = MethodID_Math_IsInf
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Math_Abs:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Abs(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Ceil:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Ceil(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Floor:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Floor(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Round:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Round(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Sqrt:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Sqrt(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Pow:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		var y float64
		y = float64(reqBuf.ReadFloat64())
		r0 := impl.Pow(x, y)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Min:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		var y float64
		y = float64(reqBuf.ReadFloat64())
		r0 := impl.Min(x, y)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Max:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		var y float64
		y = float64(reqBuf.ReadFloat64())
		r0 := impl.Max(x, y)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Sin:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Sin(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Cos:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Cos(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Tan:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Tan(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Exp:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Exp(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Log:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Log(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Log10:
		var x float64
		x = float64(reqBuf.ReadFloat64())
		r0 := impl.Log10(x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_NaN:
		r0 := impl.NaN()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_IsNaN:
		var f float64
		f = float64(reqBuf.ReadFloat64())
		r0 := impl.IsNaN(f)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_Inf:
		var sign int
		{
			tmp := reqBuf.ReadVarint()
			sign = int(tmp)
		}
		r0 := impl.Inf(sign)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Math_IsInf:
		var f float64
		f = float64(reqBuf.ReadFloat64())
		var sign int
		{
			tmp := reqBuf.ReadVarint()
			sign = int(tmp)
		}
		r0 := impl.IsInf(f, sign)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBool(bool(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Math_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Abs", 1, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Ceil", 2, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Floor", 3, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Round", 4, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Sqrt", 5, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Pow", 6, runtime.MustParseRuntimeFuncSigWithModes("function(Float64, Float64) Float64", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Min", 7, runtime.MustParseRuntimeFuncSigWithModes("function(Float64, Float64) Float64", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Max", 8, runtime.MustParseRuntimeFuncSigWithModes("function(Float64, Float64) Float64", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Sin", 9, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Cos", 10, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Tan", 11, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Exp", 12, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Log", 13, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"Log10", 14, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Float64", runtime.FFIParamIn), ""},
	{"NaN", 15, runtime.MustParseRuntimeFuncSig("function() Float64"), ""},
	{"IsNaN", 16, runtime.MustParseRuntimeFuncSigWithModes("function(Float64) Bool", runtime.FFIParamIn), ""},
	{"Inf", 17, runtime.MustParseRuntimeFuncSigWithModes("function(Int64) Float64", runtime.FFIParamIn), ""},
	{"IsInf", 18, runtime.MustParseRuntimeFuncSigWithModes("function(Float64, Int64) Bool", runtime.FFIParamIn, runtime.FFIParamIn), ""},
}

type Math_Bridge struct {
	Impl     Math
	Registry *ffigo.HandleRegistry
}

func (b *Math_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return MathHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *Math_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return MathHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *Math_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterMath(executor interface{ RegisterConstant(string, string) }, impl Math, registry *ffigo.HandleRegistry) {
	bridge := &Math_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
		RegisterInterfaceSchema(string, *runtime.RuntimeInterfaceSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registrar.RegisterFFISchema("math.Abs", bridge, Math_FFI_Schemas[0].MethodID, Math_FFI_Schemas[0].Sig, Math_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("math.Ceil", bridge, Math_FFI_Schemas[1].MethodID, Math_FFI_Schemas[1].Sig, Math_FFI_Schemas[1].Doc)
	registrar.RegisterFFISchema("math.Floor", bridge, Math_FFI_Schemas[2].MethodID, Math_FFI_Schemas[2].Sig, Math_FFI_Schemas[2].Doc)
	registrar.RegisterFFISchema("math.Round", bridge, Math_FFI_Schemas[3].MethodID, Math_FFI_Schemas[3].Sig, Math_FFI_Schemas[3].Doc)
	registrar.RegisterFFISchema("math.Sqrt", bridge, Math_FFI_Schemas[4].MethodID, Math_FFI_Schemas[4].Sig, Math_FFI_Schemas[4].Doc)
	registrar.RegisterFFISchema("math.Pow", bridge, Math_FFI_Schemas[5].MethodID, Math_FFI_Schemas[5].Sig, Math_FFI_Schemas[5].Doc)
	registrar.RegisterFFISchema("math.Min", bridge, Math_FFI_Schemas[6].MethodID, Math_FFI_Schemas[6].Sig, Math_FFI_Schemas[6].Doc)
	registrar.RegisterFFISchema("math.Max", bridge, Math_FFI_Schemas[7].MethodID, Math_FFI_Schemas[7].Sig, Math_FFI_Schemas[7].Doc)
	registrar.RegisterFFISchema("math.Sin", bridge, Math_FFI_Schemas[8].MethodID, Math_FFI_Schemas[8].Sig, Math_FFI_Schemas[8].Doc)
	registrar.RegisterFFISchema("math.Cos", bridge, Math_FFI_Schemas[9].MethodID, Math_FFI_Schemas[9].Sig, Math_FFI_Schemas[9].Doc)
	registrar.RegisterFFISchema("math.Tan", bridge, Math_FFI_Schemas[10].MethodID, Math_FFI_Schemas[10].Sig, Math_FFI_Schemas[10].Doc)
	registrar.RegisterFFISchema("math.Exp", bridge, Math_FFI_Schemas[11].MethodID, Math_FFI_Schemas[11].Sig, Math_FFI_Schemas[11].Doc)
	registrar.RegisterFFISchema("math.Log", bridge, Math_FFI_Schemas[12].MethodID, Math_FFI_Schemas[12].Sig, Math_FFI_Schemas[12].Doc)
	registrar.RegisterFFISchema("math.Log10", bridge, Math_FFI_Schemas[13].MethodID, Math_FFI_Schemas[13].Sig, Math_FFI_Schemas[13].Doc)
	registrar.RegisterFFISchema("math.NaN", bridge, Math_FFI_Schemas[14].MethodID, Math_FFI_Schemas[14].Sig, Math_FFI_Schemas[14].Doc)
	registrar.RegisterFFISchema("math.IsNaN", bridge, Math_FFI_Schemas[15].MethodID, Math_FFI_Schemas[15].Sig, Math_FFI_Schemas[15].Doc)
	registrar.RegisterFFISchema("math.Inf", bridge, Math_FFI_Schemas[16].MethodID, Math_FFI_Schemas[16].Sig, Math_FFI_Schemas[16].Doc)
	registrar.RegisterFFISchema("math.IsInf", bridge, Math_FFI_Schemas[17].MethodID, Math_FFI_Schemas[17].Sig, Math_FFI_Schemas[17].Doc)
	executor.RegisterConstant("math.E", ffigo.ToConstantString(2.71828182845904523536))
	executor.RegisterConstant("math.Pi", ffigo.ToConstantString(3.14159265358979323846))
}
