// Code generated by ffigen. DO NOT EDIT.
package errorslib

import (
	"fmt"
	"gopkg.d7z.net/go-mini/core/ffigo"
)

const (
	MethodID_Errors_New = 1
)

type ErrorsProxy struct {
	bridge ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *ErrorsProxy) New(text string) (error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(text)

	_, err := p.bridge.Call(MethodID_Errors_New, buf.Bytes())
	if err != nil {
		return err
	}

	return nil
}

func ErrorsHostRouter(impl Errors, registry *ffigo.HandleRegistry, methodID uint32, args []byte) ([]byte, error) {
	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Errors_New:
		var text string
	text = reqBuf.ReadString()
		err := impl.New(text)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			resBuf.WriteByte(1)
			resBuf.WriteString(err.Error())
		} else {
			resBuf.WriteByte(0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}
