// Code generated by ffigen. DO NOT EDIT.
package oslib

import (
	"context"
	"fmt"
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"strings"
)

const (
	MethodID_OS_Open      = 1
	MethodID_OS_Create    = 2
	MethodID_OS_ReadFile  = 3
	MethodID_OS_WriteFile = 4
	MethodID_OS_Remove    = 5
	MethodID_OS_Getenv    = 6
	MethodID_OS_Setenv    = 7
)

type OSProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *OSProxy) Open(ctx context.Context, name string) (*File, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(name)

	retData, err := p.bridge.Call(ctx, MethodID_OS_Open, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 *File
	if id := retBuf.ReadUint32(); id != 0 {
		if p.registry != nil {
			if obj, ok := p.registry.Get(id); ok {
				v_0 = obj.(*File)
			}
		}
	}
	var err_1 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_1 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_1 = fmt.Errorf("%s", s)
		}
	}
	return v_0, err_1
}

func (p *OSProxy) Create(ctx context.Context, name string) (*File, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(name)

	retData, err := p.bridge.Call(ctx, MethodID_OS_Create, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 *File
	if id := retBuf.ReadUint32(); id != 0 {
		if p.registry != nil {
			if obj, ok := p.registry.Get(id); ok {
				v_0 = obj.(*File)
			}
		}
	}
	var err_1 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_1 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_1 = fmt.Errorf("%s", s)
		}
	}
	return v_0, err_1
}

func (p *OSProxy) ReadFile(ctx context.Context, name string) ([]byte, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(name)

	retData, err := p.bridge.Call(ctx, MethodID_OS_ReadFile, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return nil, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	var err_1 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_1 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_1 = fmt.Errorf("%s", s)
		}
	}
	return v_0, err_1
}

func (p *OSProxy) WriteFile(ctx context.Context, name string, data []byte) error {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(name)
	buf.WriteBytes(data)

	retData, err := p.bridge.Call(ctx, MethodID_OS_WriteFile, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return err
	}
	retBuf := ffigo.NewReader(retData)
	var err_0 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_0 = obj.(error)
				} else {
					err_0 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_0 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_0 = fmt.Errorf("%s", s)
		}
	}
	return err_0
}

func (p *OSProxy) Remove(ctx context.Context, name string) error {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(name)

	retData, err := p.bridge.Call(ctx, MethodID_OS_Remove, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return err
	}
	retBuf := ffigo.NewReader(retData)
	var err_0 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_0 = obj.(error)
				} else {
					err_0 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_0 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_0 = fmt.Errorf("%s", s)
		}
	}
	return err_0
}

func (p *OSProxy) Getenv(ctx context.Context, key string) string {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(key)

	retData, err := p.bridge.Call(ctx, MethodID_OS_Getenv, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 string
	v_0 = retBuf.ReadString()
	return v_0
}

func (p *OSProxy) Setenv(ctx context.Context, key string, value string) error {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteString(key)
	buf.WriteString(value)

	retData, err := p.bridge.Call(ctx, MethodID_OS_Setenv, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return err
	}
	retBuf := ffigo.NewReader(retData)
	var err_0 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_0 = obj.(error)
				} else {
					err_0 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_0 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_0 = fmt.Errorf("%s", s)
		}
	}
	return err_0
}

func OSHostRouter(ctx context.Context, impl OS, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) ([]byte, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Open":
			methodID = MethodID_OS_Open
		case "Create":
			methodID = MethodID_OS_Create
		case "ReadFile":
			methodID = MethodID_OS_ReadFile
		case "WriteFile":
			methodID = MethodID_OS_WriteFile
		case "Remove":
			methodID = MethodID_OS_Remove
		case "Getenv":
			methodID = MethodID_OS_Getenv
		case "Setenv":
			methodID = MethodID_OS_Setenv
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_OS_Open:
		var name string
		name = reqBuf.ReadString()
		r0, err := impl.Open(ctx, name)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUint32(registry.Register(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_OS_Create:
		var name string
		name = reqBuf.ReadString()
		r0, err := impl.Create(ctx, name)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteUint32(registry.Register(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_OS_ReadFile:
		var name string
		name = reqBuf.ReadString()
		r0, err := impl.ReadFile(ctx, name)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_OS_WriteFile:
		var name string
		name = reqBuf.ReadString()
		var data []byte
		data = reqBuf.ReadBytes()
		err := impl.WriteFile(ctx, name, data)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_OS_Remove:
		var name string
		name = reqBuf.ReadString()
		err := impl.Remove(ctx, name)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_OS_Getenv:
		var key string
		key = reqBuf.ReadString()
		r0 := impl.Getenv(key)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(r0)
		return resBuf.Bytes(), nil
	case MethodID_OS_Setenv:
		var key string
		key = reqBuf.ReadString()
		var value string
		value = reqBuf.ReadString()
		err := impl.Setenv(key, value)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var OS_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
	Doc      string
}{
	{"Open", 1, "function(String) tuple(Ptr<File>, Error)", ""},
	{"Create", 2, "function(String) tuple(Ptr<File>, Error)", ""},
	{"ReadFile", 3, "function(String) tuple(TypeBytes, Error)", ""},
	{"WriteFile", 4, "function(String, TypeBytes) Error", ""},
	{"Remove", 5, "function(String) Error", ""},
	{"Getenv", 6, "function(String) String", ""},
	{"Setenv", 7, "function(String, String) Error", ""},
}

type OS_Bridge struct {
	Impl     OS
	Registry *ffigo.HandleRegistry
}

func (b *OS_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return OSHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *OS_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return OSHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *OS_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterOS(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType, string)
}, impl OS, registry *ffigo.HandleRegistry) {
	bridge := &OS_Bridge{Impl: impl, Registry: registry}
	prefix := "os"
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range OS_FFI_Metadata {
		executor.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec), m.Doc)
	}
}

const (
	MethodID_FileMethods_Read  = 1
	MethodID_FileMethods_Write = 2
	MethodID_FileMethods_Close = 3
)

type FileMethodsProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func (p *FileMethodsProxy) Read(ctx context.Context, f *File, b []byte) (int, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	if p.registry != nil {
		buf.WriteUint32(p.registry.Register(f))
	} else {
		buf.WriteUint32(0)
	}
	buf.WriteBytes(b)

	retData, err := p.bridge.Call(ctx, MethodID_FileMethods_Read, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int
	v_0 = int(retBuf.ReadInt64())
	var err_1 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_1 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_1 = fmt.Errorf("%s", s)
		}
	}
	return v_0, err_1
}

func (p *FileMethodsProxy) Write(ctx context.Context, f *File, b []byte) (int, error) {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	if p.registry != nil {
		buf.WriteUint32(p.registry.Register(f))
	} else {
		buf.WriteUint32(0)
	}
	buf.WriteBytes(b)

	retData, err := p.bridge.Call(ctx, MethodID_FileMethods_Write, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return 0, err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 int
	v_0 = int(retBuf.ReadInt64())
	var err_1 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_1 = obj.(error)
				} else {
					err_1 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_1 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_1 = fmt.Errorf("%s", s)
		}
	}
	return v_0, err_1
}

func (p *FileMethodsProxy) Close(ctx context.Context, f *File) error {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	if p.registry != nil {
		buf.WriteUint32(p.registry.Register(f))
	} else {
		buf.WriteUint32(0)
	}

	retData, err := p.bridge.Call(ctx, MethodID_FileMethods_Close, buf.Bytes())
	_ = retData
	_ = err
	if err != nil {
		return err
	}
	retBuf := ffigo.NewReader(retData)
	var err_0 error
	if rawErr := retBuf.ReadAny(); rawErr != nil {
		if ed, ok := rawErr.(ffigo.ErrorData); ok {
			if ed.Handle != 0 && p.registry != nil {
				if obj, ok := p.registry.Get(ed.Handle); ok {
					err_0 = obj.(error)
				} else {
					err_0 = fmt.Errorf("%s", ed.Message)
				}
			} else {
				err_0 = fmt.Errorf("%s", ed.Message)
			}
		} else if s, ok := rawErr.(string); ok && s != "" {
			err_0 = fmt.Errorf("%s", s)
		}
	}
	return err_0
}

func FileMethodsHostRouter(ctx context.Context, impl FileMethods, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) ([]byte, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Read":
			methodID = MethodID_FileMethods_Read
		case "Write":
			methodID = MethodID_FileMethods_Write
		case "Close":
			methodID = MethodID_FileMethods_Close
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_FileMethods_Read:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Read(f, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteInt64(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_FileMethods_Write:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		var b []byte
		b = reqBuf.ReadBytes()
		r0, err := impl.Write(f, b)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteInt64(int64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	case MethodID_FileMethods_Close:
		var f *File
		if id := reqBuf.ReadUint32(); id != 0 {
			if obj, ok := registry.Get(id); ok {
				f = obj.(*File)
			} else {
				return nil, fmt.Errorf("invalid handle ID: %d", id)
			}
		}
		err := impl.Close(f)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteError(err.Error(), 0)
			}
		} else {
			resBuf.WriteAny("")
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var FileMethods_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
	Doc      string
}{
	{"Read", 1, "function(Ptr<File>, TypeBytes) tuple(Int64, Error)", ""},
	{"Write", 2, "function(Ptr<File>, TypeBytes) tuple(Int64, Error)", ""},
	{"Close", 3, "function(Ptr<File>) Error", ""},
}

type FileMethods_Bridge struct {
	Impl     FileMethods
	Registry *ffigo.HandleRegistry
}

func (b *FileMethods_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return FileMethodsHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *FileMethods_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return FileMethodsHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *FileMethods_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterFileMethods(executor interface {
	RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType, string)
}, impl FileMethods, registry *ffigo.HandleRegistry) {
	bridge := &FileMethods_Bridge{Impl: impl, Registry: registry}
	prefix := "__method_File"
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range FileMethods_FFI_Metadata {
		executor.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec), m.Doc)
	}
}
