// Code generated by ffigen. DO NOT EDIT.
package sha256lib

import (
	"context"
	"crypto/sha256"
	"fmt"
	"strings"
)
import (
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

const (
	MethodID_SHA256_Sum256 = 1
)

type SHA256Proxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewSHA256Proxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) SHA256 {
	return &SHA256Proxy{bridge: bridge, registry: registry}
}

func (__p *SHA256Proxy) Sum256(data []byte) []byte {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteBytes(data)

	retData, err := __p.bridge.Call(context.Background(), MethodID_SHA256_Sum256, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 []byte
	v_0 = retBuf.ReadBytes()
	return v_0
}

func SHA256HostRouter(ctx context.Context, impl SHA256, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Sum256":
			methodID = MethodID_SHA256_Sum256
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_SHA256_Sum256:
		var data []byte
		data = reqBuf.ReadBytes()
		r0 := impl.Sum256(data)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var SHA256_FFI_Metadata = []struct {
	Name     string
	MethodID uint32
	Spec     string
	Doc      string
}{
	{"Sum256", 1, "function(TypeBytes) TypeBytes", ""},
}

var SHA256_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Sum256", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(TypeBytes) TypeBytes")), ""},
}

type SHA256_Bridge struct {
	Impl     SHA256
	Registry *ffigo.HandleRegistry
}

func (b *SHA256_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return SHA256HostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *SHA256_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return SHA256HostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *SHA256_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterSHA256(executor interface{ RegisterConstant(string, string) }, impl SHA256, registry *ffigo.HandleRegistry) {
	bridge := &SHA256_Bridge{Impl: impl, Registry: registry}
	schemaRegistrar, hasSchema := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	legacyRegistrar, hasLegacy := executor.(interface {
		RegisterFFI(string, ffigo.FFIBridge, uint32, ast.GoMiniType, string)
		RegisterStructSpec(string, ast.GoMiniType)
	})
	if !hasSchema && !hasLegacy {
		panic("ffigen: executor does not support FFI registration")
	}
	prefix := "crypto/sha256"
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	if hasSchema {
		for _, m := range SHA256_FFI_Schemas {
			schemaRegistrar.RegisterFFISchema(prefix+sep+m.Name, bridge, m.MethodID, m.Sig, m.Doc)
		}
	} else {
		for _, m := range SHA256_FFI_Metadata {
			legacyRegistrar.RegisterFFI(prefix+sep+m.Name, bridge, m.MethodID, ast.GoMiniType(m.Spec), m.Doc)
		}
	}
	executor.RegisterConstant("crypto/sha256.BlockSize", ffigo.ToConstantString(sha256.BlockSize))
	executor.RegisterConstant("crypto/sha256.Size", ffigo.ToConstantString(sha256.Size))
}
