// Code generated by ffigen. DO NOT EDIT.
package imagelib

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

var image_Image_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("image.Image", runtime.StructOwnershipHostOpaque, "struct { Bounds function(HostRef<image.Image>) tuple(Int64, Int64, Int64, Int64); Size function(HostRef<image.Image>) tuple(Int64, Int64); Width function(HostRef<image.Image>) Int64; Height function(HostRef<image.Image>) Int64; At function(HostRef<image.Image>, Int64, Int64) tuple(Int64, Int64, Int64, Int64); Set function(HostRef<image.Image>, Int64, Int64, Int64, Int64, Int64, Int64) Void; Fill function(HostRef<image.Image>, Int64, Int64, Int64, Int64) Void; Clear function(HostRef<image.Image>) Void; Clone function(HostRef<image.Image>) HostRef<image.Image>; SubImage function(HostRef<image.Image>, Int64, Int64, Int64, Int64) tuple(HostRef<image.Image>, Error); Draw function(HostRef<image.Image>, HostRef<image.Image>, Int64, Int64) Void; Resize function(HostRef<image.Image>, Int64, Int64) tuple(HostRef<image.Image>, Error); Crop function(HostRef<image.Image>, Int64, Int64, Int64, Int64) tuple(HostRef<image.Image>, Error); EncodePNG function(HostRef<image.Image>) tuple(TypeBytes, Error); EncodeJPEG function(HostRef<image.Image>, Int64) tuple(TypeBytes, Error); }")

const (
	MethodID_ImageLib_Decode  = 1
	MethodID_ImageLib_NewRGBA = 2
)

type ImageLibProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewImageLibProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) ImageLib {
	return &ImageLibProxy{bridge: bridge, registry: registry}
}

func (__p *ImageLibProxy) Decode(ctx context.Context, data []byte) (*Image, string, error) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteBytes(data)

	__ret, err := __p.bridge.Call(ctx, &ffigo.FFICallRequest{MethodID: MethodID_ImageLib_Decode, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	if err != nil {
		return nil, "", err
	}
	retBuf := ffigo.NewReader(retData)
	var v_0 *Image
	// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.GetTyped(id, "image.Image"); ok {
				v_0 = obj.(*Image)
			}
		}
	}
	var v_1 string
	v_1 = string(retBuf.ReadString())
	var err_2 error
	if retBuf.Available() > 0 {
		ed := retBuf.ReadRawError()
		if ed.Message != "" || ed.Handle != 0 {
			if ed.Handle != 0 && __p.registry != nil {
				if obj, ok := __p.registry.Get(ed.Handle); ok {
					err_2 = obj.(error)
				} else {
					err_2 = ed
				}
			} else {
				err_2 = ed
			}
		}
	}
	return v_0, v_1, err_2
}

func (__p *ImageLibProxy) NewRGBA(ctx context.Context, width int, height int) *Image {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteVarint(int64(width))
	wireBuf.WriteVarint(int64(height))

	__ret, err := __p.bridge.Call(ctx, &ffigo.FFICallRequest{MethodID: MethodID_ImageLib_NewRGBA, Args: append([]byte(nil), wireBuf.Bytes()...)})
	retData, syncErr := ffigo.SyncBytes(__ret)
	if err == nil {
		err = syncErr
	}
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 *Image
	// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
	if id := uint32(retBuf.ReadUvarint()); id != 0 {
		if __p.registry != nil {
			if obj, ok := __p.registry.GetTyped(id, "image.Image"); ok {
				v_0 = obj.(*Image)
			}
		}
	}
	return v_0
}

func ImageLibHostRouter(ctx context.Context, impl ImageLib, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Decode":
			methodID = MethodID_ImageLib_Decode
		case "NewRGBA":
			methodID = MethodID_ImageLib_NewRGBA
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_ImageLib_Decode:
		var data []byte
		data = reqBuf.ReadBytes()
		r0, r1, err := impl.Decode(ctx, data)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "image.Image")))
		}
		resBuf.WriteString(string(r1))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_ImageLib_NewRGBA:
		var width int
		{
			tmp := reqBuf.ReadVarint()
			width = int(tmp)
		}
		var height int
		{
			tmp := reqBuf.ReadVarint()
			height = int(tmp)
		}
		r0 := impl.NewRGBA(ctx, width, height)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "image.Image")))
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var ImageLib_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Decode", 1, runtime.MustParseRuntimeFuncSigWithModes("function(TypeBytes) tuple(HostRef<image.Image>, String, Error)", runtime.FFIParamIn), "Decode 对应 Go 的 image.Decode(r) (Image, string, error)"},
	{"NewRGBA", 2, runtime.MustParseRuntimeFuncSigWithModes("function(Int64, Int64) HostRef<image.Image>", runtime.FFIParamIn, runtime.FFIParamIn), "NewRGBA 对应 Go 的 image.NewRGBA(rect)"},
}

type ImageLib_Bridge struct {
	Impl     ImageLib
	Registry *ffigo.HandleRegistry
}

func (b *ImageLib_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ImageLibHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *ImageLib_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ImageLibHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *ImageLib_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceImageLib(impl ImageLib) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddFunc("image", "Decode", "image.Decode", ImageLib_FFI_Schemas[0].MethodID, ImageLib_FFI_Schemas[0].Sig, ImageLib_FFI_Schemas[0].Doc)
	schema.AddFunc("image", "NewRGBA", "image.NewRGBA", ImageLib_FFI_Schemas[1].MethodID, ImageLib_FFI_Schemas[1].Sig, ImageLib_FFI_Schemas[1].Doc)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &ImageLib_Bridge{Impl: impl, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.AddRoute("image", "Decode", runtime.FFIRoute{Name: "image.Decode", Bridge: bridge, MethodID: ImageLib_FFI_Schemas[0].MethodID, FuncSig: ImageLib_FFI_Schemas[0].Sig, Doc: ImageLib_FFI_Schemas[0].Doc})
		bound.AddRoute("image", "NewRGBA", runtime.FFIRoute{Name: "image.NewRGBA", Bridge: bridge, MethodID: ImageLib_FFI_Schemas[1].MethodID, FuncSig: ImageLib_FFI_Schemas[1].Sig, Doc: ImageLib_FFI_Schemas[1].Doc})
		return bound, nil
	})
}

const (
	MethodID_Image_Bounds     = 1
	MethodID_Image_Size       = 2
	MethodID_Image_Width      = 3
	MethodID_Image_Height     = 4
	MethodID_Image_At         = 5
	MethodID_Image_Set        = 6
	MethodID_Image_Fill       = 7
	MethodID_Image_Clear      = 8
	MethodID_Image_Clone      = 9
	MethodID_Image_SubImage   = 10
	MethodID_Image_Draw       = 11
	MethodID_Image_Resize     = 12
	MethodID_Image_Crop       = 13
	MethodID_Image_EncodePNG  = 14
	MethodID_Image_EncodeJPEG = 15
)

func ImageHostRouter(ctx context.Context, impl *Image, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Bounds":
			methodID = MethodID_Image_Bounds
		case "Size":
			methodID = MethodID_Image_Size
		case "Width":
			methodID = MethodID_Image_Width
		case "Height":
			methodID = MethodID_Image_Height
		case "At":
			methodID = MethodID_Image_At
		case "Set":
			methodID = MethodID_Image_Set
		case "Fill":
			methodID = MethodID_Image_Fill
		case "Clear":
			methodID = MethodID_Image_Clear
		case "Clone":
			methodID = MethodID_Image_Clone
		case "SubImage":
			methodID = MethodID_Image_SubImage
		case "Draw":
			methodID = MethodID_Image_Draw
		case "Resize":
			methodID = MethodID_Image_Resize
		case "Crop":
			methodID = MethodID_Image_Crop
		case "EncodePNG":
			methodID = MethodID_Image_EncodePNG
		case "EncodeJPEG":
			methodID = MethodID_Image_EncodeJPEG
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Image_Bounds:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0, r1, r2, r3 := __recv.Bounds()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		resBuf.WriteVarint(int64(r1))
		resBuf.WriteVarint(int64(r2))
		resBuf.WriteVarint(int64(r3))
		return resBuf.Bytes(), nil
	case MethodID_Image_Size:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0, r1 := __recv.Size()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		resBuf.WriteVarint(int64(r1))
		return resBuf.Bytes(), nil
	case MethodID_Image_Width:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Width()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Image_Height:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Height()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Image_At:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var x int
		{
			tmp := reqBuf.ReadVarint()
			x = int(tmp)
		}
		var y int
		{
			tmp := reqBuf.ReadVarint()
			y = int(tmp)
		}
		r0, r1, r2, r3 := __recv.At(x, y)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		resBuf.WriteVarint(int64(r1))
		resBuf.WriteVarint(int64(r2))
		resBuf.WriteVarint(int64(r3))
		return resBuf.Bytes(), nil
	case MethodID_Image_Set:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var x int
		{
			tmp := reqBuf.ReadVarint()
			x = int(tmp)
		}
		var y int
		{
			tmp := reqBuf.ReadVarint()
			y = int(tmp)
		}
		var r int
		{
			tmp := reqBuf.ReadVarint()
			r = int(tmp)
		}
		var g int
		{
			tmp := reqBuf.ReadVarint()
			g = int(tmp)
		}
		var b int
		{
			tmp := reqBuf.ReadVarint()
			b = int(tmp)
		}
		var a int
		{
			tmp := reqBuf.ReadVarint()
			a = int(tmp)
		}
		__recv.Set(x, y, r, g, b, a)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Image_Fill:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var r int
		{
			tmp := reqBuf.ReadVarint()
			r = int(tmp)
		}
		var g int
		{
			tmp := reqBuf.ReadVarint()
			g = int(tmp)
		}
		var b int
		{
			tmp := reqBuf.ReadVarint()
			b = int(tmp)
		}
		var a int
		{
			tmp := reqBuf.ReadVarint()
			a = int(tmp)
		}
		__recv.Fill(r, g, b, a)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Image_Clear:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		__recv.Clear()
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Image_Clone:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.Clone()
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "image.Image")))
		}
		return resBuf.Bytes(), nil
	case MethodID_Image_SubImage:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var x int
		{
			tmp := reqBuf.ReadVarint()
			x = int(tmp)
		}
		var y int
		{
			tmp := reqBuf.ReadVarint()
			y = int(tmp)
		}
		var width int
		{
			tmp := reqBuf.ReadVarint()
			width = int(tmp)
		}
		var height int
		{
			tmp := reqBuf.ReadVarint()
			height = int(tmp)
		}
		r0, err := __recv.SubImage(x, y, width, height)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "image.Image")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Image_Draw:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var src *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				src = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "src", err)
			}
		}
		var x int
		{
			tmp := reqBuf.ReadVarint()
			x = int(tmp)
		}
		var y int
		{
			tmp := reqBuf.ReadVarint()
			y = int(tmp)
		}
		__recv.Draw(ctx, src, x, y)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Image_Resize:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var width int
		{
			tmp := reqBuf.ReadVarint()
			width = int(tmp)
		}
		var height int
		{
			tmp := reqBuf.ReadVarint()
			height = int(tmp)
		}
		r0, err := __recv.Resize(width, height)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "image.Image")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Image_Crop:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var x int
		{
			tmp := reqBuf.ReadVarint()
			x = int(tmp)
		}
		var y int
		{
			tmp := reqBuf.ReadVarint()
			y = int(tmp)
		}
		var width int
		{
			tmp := reqBuf.ReadVarint()
			width = int(tmp)
		}
		var height int
		{
			tmp := reqBuf.ReadVarint()
			height = int(tmp)
		}
		r0, err := __recv.Crop(x, y, width, height)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "image.Image")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Image_EncodePNG:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0, err := __recv.EncodePNG()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case MethodID_Image_EncodeJPEG:
		var __recv *Image
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "image.Image"); err == nil {
				__recv = obj.(*Image)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var quality int
		{
			tmp := reqBuf.ReadVarint()
			quality = int(tmp)
		}
		r0, err := __recv.EncodeJPEG(quality)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteBytes(r0)
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Image_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Bounds", 1, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) tuple(Int64, Int64, Int64, Int64)", runtime.FFIParamIn), "Bounds 返回 x1, y1, x2, y2 (对应 Go 的 Bounds() Rectangle)"},
	{"Size", 2, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) tuple(Int64, Int64)", runtime.FFIParamIn), "Size 返回 width, height"},
	{"Width", 3, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) Int64", runtime.FFIParamIn), "Width 返回图像宽度"},
	{"Height", 4, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) Int64", runtime.FFIParamIn), "Height 返回图像高度"},
	{"At", 5, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64, Int64) tuple(Int64, Int64, Int64, Int64)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "At 返回 r, g, b, a (0-255)"},
	{"Set", 6, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64, Int64, Int64, Int64, Int64, Int64) Void", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "Set 设置指定像素的颜色"},
	{"Fill", 7, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64, Int64, Int64, Int64) Void", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "Fill 用指定颜色填充整个图像"},
	{"Clear", 8, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) Void", runtime.FFIParamIn), "Clear 将图像清空为透明"},
	{"Clone", 9, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) HostRef<image.Image>", runtime.FFIParamIn), "Clone 复制当前图像"},
	{"SubImage", 10, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64, Int64, Int64, Int64) tuple(HostRef<image.Image>, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "SubImage 返回图像的子部分 (共享内存)"},
	{"Draw", 11, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, HostRef<image.Image>, Int64, Int64) Void", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "Draw 将另一张图像绘制到当前图像上 (支持透明度叠加)"},
	{"Resize", 12, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64, Int64) tuple(HostRef<image.Image>, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "Resize 缩放图像"},
	{"Crop", 13, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64, Int64, Int64, Int64) tuple(HostRef<image.Image>, Error)", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "Crop 裁剪图像"},
	{"EncodePNG", 14, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>) tuple(TypeBytes, Error)", runtime.FFIParamIn), "EncodePNG 将图像编码为 PNG 字节数组"},
	{"EncodeJPEG", 15, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<image.Image>, Int64) tuple(TypeBytes, Error)", runtime.FFIParamIn, runtime.FFIParamIn), "EncodeJPEG 将图像编码为 JPEG 字节数组"},
}

type Image_Bridge struct {
	Impl     *Image
	Registry *ffigo.HandleRegistry
}

func (b *Image_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ImageHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Image_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return ImageHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Image_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceImage() *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddStruct("image.Image", image_Image_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &Image_Bridge{Impl: nil, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.Routes["image.Image.Bounds"] = runtime.FFIRoute{Name: "image.Image.Bounds", Bridge: bridge, MethodID: Image_FFI_Schemas[0].MethodID, FuncSig: Image_FFI_Schemas[0].Sig, Doc: Image_FFI_Schemas[0].Doc}
		bound.Routes["image.Image.Size"] = runtime.FFIRoute{Name: "image.Image.Size", Bridge: bridge, MethodID: Image_FFI_Schemas[1].MethodID, FuncSig: Image_FFI_Schemas[1].Sig, Doc: Image_FFI_Schemas[1].Doc}
		bound.Routes["image.Image.Width"] = runtime.FFIRoute{Name: "image.Image.Width", Bridge: bridge, MethodID: Image_FFI_Schemas[2].MethodID, FuncSig: Image_FFI_Schemas[2].Sig, Doc: Image_FFI_Schemas[2].Doc}
		bound.Routes["image.Image.Height"] = runtime.FFIRoute{Name: "image.Image.Height", Bridge: bridge, MethodID: Image_FFI_Schemas[3].MethodID, FuncSig: Image_FFI_Schemas[3].Sig, Doc: Image_FFI_Schemas[3].Doc}
		bound.Routes["image.Image.At"] = runtime.FFIRoute{Name: "image.Image.At", Bridge: bridge, MethodID: Image_FFI_Schemas[4].MethodID, FuncSig: Image_FFI_Schemas[4].Sig, Doc: Image_FFI_Schemas[4].Doc}
		bound.Routes["image.Image.Set"] = runtime.FFIRoute{Name: "image.Image.Set", Bridge: bridge, MethodID: Image_FFI_Schemas[5].MethodID, FuncSig: Image_FFI_Schemas[5].Sig, Doc: Image_FFI_Schemas[5].Doc}
		bound.Routes["image.Image.Fill"] = runtime.FFIRoute{Name: "image.Image.Fill", Bridge: bridge, MethodID: Image_FFI_Schemas[6].MethodID, FuncSig: Image_FFI_Schemas[6].Sig, Doc: Image_FFI_Schemas[6].Doc}
		bound.Routes["image.Image.Clear"] = runtime.FFIRoute{Name: "image.Image.Clear", Bridge: bridge, MethodID: Image_FFI_Schemas[7].MethodID, FuncSig: Image_FFI_Schemas[7].Sig, Doc: Image_FFI_Schemas[7].Doc}
		bound.Routes["image.Image.Clone"] = runtime.FFIRoute{Name: "image.Image.Clone", Bridge: bridge, MethodID: Image_FFI_Schemas[8].MethodID, FuncSig: Image_FFI_Schemas[8].Sig, Doc: Image_FFI_Schemas[8].Doc}
		bound.Routes["image.Image.SubImage"] = runtime.FFIRoute{Name: "image.Image.SubImage", Bridge: bridge, MethodID: Image_FFI_Schemas[9].MethodID, FuncSig: Image_FFI_Schemas[9].Sig, Doc: Image_FFI_Schemas[9].Doc}
		bound.Routes["image.Image.Draw"] = runtime.FFIRoute{Name: "image.Image.Draw", Bridge: bridge, MethodID: Image_FFI_Schemas[10].MethodID, FuncSig: Image_FFI_Schemas[10].Sig, Doc: Image_FFI_Schemas[10].Doc}
		bound.Routes["image.Image.Resize"] = runtime.FFIRoute{Name: "image.Image.Resize", Bridge: bridge, MethodID: Image_FFI_Schemas[11].MethodID, FuncSig: Image_FFI_Schemas[11].Sig, Doc: Image_FFI_Schemas[11].Doc}
		bound.Routes["image.Image.Crop"] = runtime.FFIRoute{Name: "image.Image.Crop", Bridge: bridge, MethodID: Image_FFI_Schemas[12].MethodID, FuncSig: Image_FFI_Schemas[12].Sig, Doc: Image_FFI_Schemas[12].Doc}
		bound.Routes["image.Image.EncodePNG"] = runtime.FFIRoute{Name: "image.Image.EncodePNG", Bridge: bridge, MethodID: Image_FFI_Schemas[13].MethodID, FuncSig: Image_FFI_Schemas[13].Sig, Doc: Image_FFI_Schemas[13].Doc}
		bound.Routes["image.Image.EncodeJPEG"] = runtime.FFIRoute{Name: "image.Image.EncodeJPEG", Bridge: bridge, MethodID: Image_FFI_Schemas[14].MethodID, FuncSig: Image_FFI_Schemas[14].Sig, Doc: Image_FFI_Schemas[14].Doc}
		bound.AddStruct("image.Image", image_Image_FFI_StructSchema)
		return bound, nil
	})
}
