// Code generated by ffigen. DO NOT EDIT.
package ordertest

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

var order_Order_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("order.Order", runtime.StructOwnershipHostOpaque, "struct { New function(String) tuple(HostRef<order.Order>, Error); AddItem function(HostRef<order.Order>, String, Float64) Error; GetTotal function(HostRef<order.Order>) tuple(Float64, Error); Close function(HostRef<order.Order>) Error; }")

const (
	methodIDOrderServiceNew      = 1
	methodIDOrderServiceAddItem  = 2
	methodIDOrderServiceGetTotal = 3
	methodIDOrderServiceClose    = 4
)

func orderServiceHostRouter(ctx context.Context, impl OrderService, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "New":
			methodID = methodIDOrderServiceNew
		case "AddItem":
			methodID = methodIDOrderServiceAddItem
		case "GetTotal":
			methodID = methodIDOrderServiceGetTotal
		case "Close":
			methodID = methodIDOrderServiceClose
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case methodIDOrderServiceNew:
		var id string
		id = string(reqBuf.ReadString())
		r0, err := impl.New(id)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "order.Order")))
		}
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDOrderServiceAddItem:
		var o *Order
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "order.Order"); err == nil {
				o = obj.(*Order)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "o", err)
			}
		}
		var name string
		name = string(reqBuf.ReadString())
		var price float64
		price = float64(reqBuf.ReadFloat64())
		err := impl.AddItem(o, name, price)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDOrderServiceGetTotal:
		var o *Order
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "order.Order"); err == nil {
				o = obj.(*Order)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "o", err)
			}
		}
		r0, err := impl.GetTotal(o)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteFloat64(float64(r0))
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	case methodIDOrderServiceClose:
		var o *Order
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "order.Order"); err == nil {
				o = obj.(*Order)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "o", err)
			}
		}
		err := impl.Close(o)
		resBuf := ffigo.GetBuffer()
		if err != nil {
			if registry != nil {
				resBuf.WriteRawError(err.Error(), registry.Register(err))
			} else {
				resBuf.WriteRawError(err.Error(), 0)
			}
		} else {
			resBuf.WriteRawError("", 0)
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var orderServiceRoutes = []runtime.FFIRouteDecl{
	{PackagePath: "order", MemberName: "New", RouteName: "order.New", MethodID: methodIDOrderServiceNew, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(String) tuple(HostRef<order.Order>, Error)", runtime.FFIParamIn), Doc: "New 创建新订单"},
	{TypeName: "order.Order", MethodName: "AddItem", RouteName: "order.Order.AddItem", MethodID: methodIDOrderServiceAddItem, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<order.Order>, String, Float64) Error", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), Doc: "AddItem 向订单添加商品 注意：这里使用 *Order 替代 uint32，ffigen 将自动处理句柄映射"},
	{TypeName: "order.Order", MethodName: "GetTotal", RouteName: "order.Order.GetTotal", MethodID: methodIDOrderServiceGetTotal, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<order.Order>) tuple(Float64, Error)", runtime.FFIParamIn), Doc: "GetTotal 获取总价"},
	{TypeName: "order.Order", MethodName: "Close", RouteName: "order.Order.Close", MethodID: methodIDOrderServiceClose, Sig: runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<order.Order>) Error", runtime.FFIParamIn), Doc: "Close 关闭订单"},
}

func SurfaceOrderService(impl OrderService) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddRouteDecls(orderServiceRoutes)
	schema.AddStruct("order.Order", order_Order_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := ffigo.NewRouterBridge(ctx.Registry, func(callCtx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
			return orderServiceHostRouter(callCtx, impl, ctx.Registry, req.MethodID, req.Method, req.Args)
		})
		bound := runtime.NewBoundFFISurfaceFromSchema(schema)
		if err := bound.BindSchemaRoutes(schema, bridge); err != nil {
			return nil, err
		}
		return bound, nil
	})
}
