// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
	"strings"
)
import (
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

const (
	MethodID_MockShapeAPI_GetRect = 1
	MethodID_MockShapeAPI_Area    = 2
)

type MockShapeAPIProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewMockShapeAPIProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) MockShapeAPI {
	return &MockShapeAPIProxy{bridge: bridge, registry: registry}
}

func (__p *MockShapeAPIProxy) GetRect() Rect {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	retData, err := __p.bridge.Call(context.Background(), MethodID_MockShapeAPI_GetRect, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 Rect
	{
		tmp := retBuf.ReadVarint()
		v_0.A.X = int64(tmp)
	}
	{
		tmp := retBuf.ReadVarint()
		v_0.A.Y = int64(tmp)
	}
	{
		tmp := retBuf.ReadVarint()
		v_0.B.X = int64(tmp)
	}
	{
		tmp := retBuf.ReadVarint()
		v_0.B.Y = int64(tmp)
	}
	return v_0
}

func (__p *MockShapeAPIProxy) Area(r Rect) int64 {
	buf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(buf)

	buf.WriteVarint(int64(r.A.X))
	buf.WriteVarint(int64(r.A.Y))
	buf.WriteVarint(int64(r.B.X))
	buf.WriteVarint(int64(r.B.Y))

	retData, err := __p.bridge.Call(context.Background(), MethodID_MockShapeAPI_Area, buf.Bytes())
	_ = retData
	_ = err
	retBuf := ffigo.NewReader(retData)
	var v_0 int64
	{
		tmp := retBuf.ReadVarint()
		v_0 = int64(tmp)
	}
	return v_0
}

func MockShapeAPIHostRouter(ctx context.Context, impl MockShapeAPI, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "GetRect":
			methodID = MethodID_MockShapeAPI_GetRect
		case "Area":
			methodID = MethodID_MockShapeAPI_Area
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_MockShapeAPI_GetRect:
		r0 := impl.GetRect()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0.A.X))
		resBuf.WriteVarint(int64(r0.A.Y))
		resBuf.WriteVarint(int64(r0.B.X))
		resBuf.WriteVarint(int64(r0.B.Y))
		return resBuf.Bytes(), nil
	case MethodID_MockShapeAPI_Area:
		var r Rect
		{
			tmp := reqBuf.ReadVarint()
			r.A.X = int64(tmp)
		}
		{
			tmp := reqBuf.ReadVarint()
			r.A.Y = int64(tmp)
		}
		{
			tmp := reqBuf.ReadVarint()
			r.B.X = int64(tmp)
		}
		{
			tmp := reqBuf.ReadVarint()
			r.B.Y = int64(tmp)
		}
		r0 := impl.Area(r)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var MockShapeAPI_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"GetRect", 1, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function() Rect")), ""},
	{"Area", 2, runtime.MustParseRuntimeFuncSig(ast.GoMiniType("function(Rect) Int64")), ""},
}

type MockShapeAPI_Bridge struct {
	Impl     MockShapeAPI
	Registry *ffigo.HandleRegistry
}

func (b *MockShapeAPI_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return MockShapeAPIHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *MockShapeAPI_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return MockShapeAPIHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *MockShapeAPI_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

var Rect_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("gopkg.d7z.net/go-mini/cmd/ffigen/tests.Rect", ast.GoMiniType("struct { A Point; B Point; }"))

var Point_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("gopkg.d7z.net/go-mini/cmd/ffigen/tests.Point", ast.GoMiniType("struct { X Int64; Y Int64; }"))

func RegisterMockShapeAPILibrary(executor interface{ RegisterConstant(string, string) }, prefix string, impl MockShapeAPI, registry *ffigo.HandleRegistry) {
	bridge := &MockShapeAPI_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	sep := "."
	if strings.HasPrefix(prefix, "__method_") {
		sep = "_"
	}
	for _, m := range MockShapeAPI_FFI_Schemas {
		registrar.RegisterFFISchema(prefix+sep+m.Name, bridge, m.MethodID, m.Sig, m.Doc)
	}
	registrar.RegisterStructSchema("gopkg.d7z.net/go-mini/cmd/ffigen/tests.Rect", Rect_FFI_StructSchema)
	registrar.RegisterStructSchema("gopkg.d7z.net/go-mini/cmd/ffigen/tests.Point", Point_FFI_StructSchema)
}
