// Code generated by ffigen. DO NOT EDIT.
package tests

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ast"
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
)

const (
	MethodID_Logger_Log      = 1
	MethodID_Logger_Internal = 2
)

type LoggerProxy struct {
	bridge   ffigo.FFIBridge
	registry *ffigo.HandleRegistry
}

func NewLoggerProxy(bridge ffigo.FFIBridge, registry *ffigo.HandleRegistry) Logger {
	return &LoggerProxy{bridge: bridge, registry: registry}
}

func (__p *LoggerProxy) Log(ctx context.Context, msg string, level string, code int64) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(msg))
	wireBuf.WriteString(string(level))
	wireBuf.WriteVarint(int64(code))

	_, err := __p.bridge.Call(ctx, MethodID_Logger_Log, wireBuf.Bytes())
	_ = err
	return
}

func (__p *LoggerProxy) Internal(arg0 string, arg1 string, arg2 int64) {
	wireBuf := ffigo.GetBuffer()
	defer ffigo.ReleaseBuffer(wireBuf)

	wireBuf.WriteString(string(arg0))
	wireBuf.WriteString(string(arg1))
	wireBuf.WriteVarint(int64(arg2))

	_, err := __p.bridge.Call(context.Background(), MethodID_Logger_Internal, wireBuf.Bytes())
	_ = err
	return
}

func LoggerHostRouter(ctx context.Context, impl Logger, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (retData []byte, bridgeErr error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Log":
			methodID = MethodID_Logger_Log
		case "Internal":
			methodID = MethodID_Logger_Internal
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Logger_Log:
		var msg string
		msg = string(reqBuf.ReadString())
		var level string
		level = string(reqBuf.ReadString())
		var code int64
		{
			tmp := reqBuf.ReadVarint()
			code = int64(tmp)
		}
		impl.Log(ctx, msg, level, code)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Logger_Internal:
		var arg0 string
		arg0 = string(reqBuf.ReadString())
		var arg1 string
		arg1 = string(reqBuf.ReadString())
		var arg2 int64
		{
			tmp := reqBuf.ReadVarint()
			arg2 = int64(tmp)
		}
		impl.Internal(arg0, arg1, arg2)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Logger_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Log", 1, runtime.MustParseRuntimeFuncSigWithModes(ast.GoMiniType("function(String, String, Int64) Void"), runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Internal", 2, runtime.MustParseRuntimeFuncSigWithModes(ast.GoMiniType("function(String, String, Int64) Void"), runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), "Internal uses unnamed parameters to test ffigen's default naming (arg0, arg1, etc.)"},
}

type Logger_Bridge struct {
	Impl     Logger
	Registry *ffigo.HandleRegistry
}

func (b *Logger_Bridge) Call(ctx context.Context, methodID uint32, args []byte) ([]byte, error) {
	return LoggerHostRouter(ctx, b.Impl, b.Registry, methodID, "", args)
}

func (b *Logger_Bridge) Invoke(ctx context.Context, method string, args []byte) ([]byte, error) {
	return LoggerHostRouter(ctx, b.Impl, b.Registry, 0, method, args)
}

func (b *Logger_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func RegisterLogger(executor interface{ RegisterConstant(string, string) }, impl Logger, registry *ffigo.HandleRegistry) {
	bridge := &Logger_Bridge{Impl: impl, Registry: registry}
	registrar, ok := executor.(interface {
		RegisterFFISchema(string, ffigo.FFIBridge, uint32, *runtime.RuntimeFuncSig, string)
		RegisterStructSchema(string, *runtime.RuntimeStructSpec)
	})
	if !ok {
		panic("ffigen: executor does not support schema FFI registration")
	}
	registrar.RegisterFFISchema("logger.Log", bridge, Logger_FFI_Schemas[0].MethodID, Logger_FFI_Schemas[0].Sig, Logger_FFI_Schemas[0].Doc)
	registrar.RegisterFFISchema("logger.Internal", bridge, Logger_FFI_Schemas[1].MethodID, Logger_FFI_Schemas[1].Sig, Logger_FFI_Schemas[1].Doc)
}
