// Code generated by ffigen. DO NOT EDIT.
package structtest

import (
	"context"
	"fmt"
)
import (
	"gopkg.d7z.net/go-mini/core/ffigo"
	"gopkg.d7z.net/go-mini/core/runtime"
	"gopkg.d7z.net/go-mini/core/surface"
)

var calc_Calculator_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("calc.Calculator", runtime.StructOwnershipHostOpaque, "struct { Add function(HostRef<calc.Calculator>, Int64) Int64; Multiply function(HostRef<calc.Calculator>, Int64, Int64) Int64; GetBase function(HostRef<calc.Calculator>) Int64; }")

var calc_Table_FFI_StructSchema = runtime.MustParseRuntimeStructSpec("calc.Table", runtime.StructOwnershipHostOpaque, "struct { SetString function(HostRef<calc.Table>, Int64, Int64, String) Void; GetString function(HostRef<calc.Table>, Int64, Int64) String; }")

const (
	MethodID_Calculator_Add      = 1
	MethodID_Calculator_Multiply = 2
	MethodID_Calculator_GetBase  = 3
)

func CalculatorHostRouter(ctx context.Context, impl *Calculator, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "Add":
			methodID = MethodID_Calculator_Add
		case "Multiply":
			methodID = MethodID_Calculator_Multiply
		case "GetBase":
			methodID = MethodID_Calculator_GetBase
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Calculator_Add:
		var __recv *Calculator
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "calc.Calculator"); err == nil {
				__recv = obj.(*Calculator)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var x int64
		{
			tmp := reqBuf.ReadVarint()
			x = int64(tmp)
		}
		r0 := __recv.Add(ctx, x)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Calculator_Multiply:
		var __recv *Calculator
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "calc.Calculator"); err == nil {
				__recv = obj.(*Calculator)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var x int64
		{
			tmp := reqBuf.ReadVarint()
			x = int64(tmp)
		}
		var y int64
		{
			tmp := reqBuf.ReadVarint()
			y = int64(tmp)
		}
		r0 := __recv.Multiply(x, y)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	case MethodID_Calculator_GetBase:
		var __recv *Calculator
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "calc.Calculator"); err == nil {
				__recv = obj.(*Calculator)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		r0 := __recv.GetBase()
		resBuf := ffigo.GetBuffer()
		resBuf.WriteVarint(int64(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Calculator_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"Add", 1, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<calc.Calculator>, Int64) Int64", runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"Multiply", 2, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<calc.Calculator>, Int64, Int64) Int64", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"GetBase", 3, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<calc.Calculator>) Int64", runtime.FFIParamIn), ""},
}

type Calculator_Bridge struct {
	Impl     *Calculator
	Registry *ffigo.HandleRegistry
}

func (b *Calculator_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return CalculatorHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Calculator_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return CalculatorHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Calculator_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceCalculator() *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddStruct("calc.Calculator", calc_Calculator_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &Calculator_Bridge{Impl: nil, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.Routes["calc.Calculator.Add"] = runtime.FFIRoute{Name: "calc.Calculator.Add", Bridge: bridge, MethodID: Calculator_FFI_Schemas[0].MethodID, FuncSig: Calculator_FFI_Schemas[0].Sig, Doc: Calculator_FFI_Schemas[0].Doc}
		bound.Routes["calc.Calculator.Multiply"] = runtime.FFIRoute{Name: "calc.Calculator.Multiply", Bridge: bridge, MethodID: Calculator_FFI_Schemas[1].MethodID, FuncSig: Calculator_FFI_Schemas[1].Sig, Doc: Calculator_FFI_Schemas[1].Doc}
		bound.Routes["calc.Calculator.GetBase"] = runtime.FFIRoute{Name: "calc.Calculator.GetBase", Bridge: bridge, MethodID: Calculator_FFI_Schemas[2].MethodID, FuncSig: Calculator_FFI_Schemas[2].Sig, Doc: Calculator_FFI_Schemas[2].Doc}
		bound.AddStruct("calc.Calculator", calc_Calculator_FFI_StructSchema)
		return bound, nil
	})
}

const (
	MethodID_Table_SetString = 1
	MethodID_Table_GetString = 2
)

func TableHostRouter(ctx context.Context, impl *Table, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "SetString":
			methodID = MethodID_Table_SetString
		case "GetString":
			methodID = MethodID_Table_GetString
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Table_SetString:
		var __recv *Table
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "calc.Table"); err == nil {
				__recv = obj.(*Table)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var row int
		{
			tmp := reqBuf.ReadVarint()
			row = int(tmp)
		}
		var col int
		{
			tmp := reqBuf.ReadVarint()
			col = int(tmp)
		}
		var val string
		val = string(reqBuf.ReadString())
		__recv.SetString(row, col, val)
		resBuf := ffigo.GetBuffer()
		return resBuf.Bytes(), nil
	case MethodID_Table_GetString:
		var __recv *Table
		// HostRef<T> is restored from the opaque handle ID written on the FFI wire.
		if id := uint32(reqBuf.ReadUvarint()); id != 0 {
			if obj, err := registry.GetTypedWithAudit(id, "calc.Table"); err == nil {
				__recv = obj.(*Table)
			} else {
				return nil, fmt.Errorf("FFI restore param '%s' failed: %v", "__recv", err)
			}
		}
		var row int
		{
			tmp := reqBuf.ReadVarint()
			row = int(tmp)
		}
		var col int
		{
			tmp := reqBuf.ReadVarint()
			col = int(tmp)
		}
		r0 := __recv.GetString(row, col)
		resBuf := ffigo.GetBuffer()
		resBuf.WriteString(string(r0))
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Table_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"SetString", 1, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<calc.Table>, Int64, Int64, String) Void", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
	{"GetString", 2, runtime.MustParseRuntimeFuncSigWithModes("function(HostRef<calc.Table>, Int64, Int64) String", runtime.FFIParamIn, runtime.FFIParamIn, runtime.FFIParamIn), ""},
}

type Table_Bridge struct {
	Impl     *Table
	Registry *ffigo.HandleRegistry
}

func (b *Table_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return TableHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Table_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return TableHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Table_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceTable() *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	schema.AddStruct("calc.Table", calc_Table_FFI_StructSchema)
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &Table_Bridge{Impl: nil, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.Routes["calc.Table.SetString"] = runtime.FFIRoute{Name: "calc.Table.SetString", Bridge: bridge, MethodID: Table_FFI_Schemas[0].MethodID, FuncSig: Table_FFI_Schemas[0].Sig, Doc: Table_FFI_Schemas[0].Doc}
		bound.Routes["calc.Table.GetString"] = runtime.FFIRoute{Name: "calc.Table.GetString", Bridge: bridge, MethodID: Table_FFI_Schemas[1].MethodID, FuncSig: Table_FFI_Schemas[1].Sig, Doc: Table_FFI_Schemas[1].Doc}
		bound.AddStruct("calc.Table", calc_Table_FFI_StructSchema)
		return bound, nil
	})
}

const (
	MethodID_Factory_New      = 1
	MethodID_Factory_NewTable = 2
)

func FactoryHostRouter(ctx context.Context, impl *Factory, registry *ffigo.HandleRegistry, methodID uint32, methodName string, args []byte) (ffigo.FFIReturn, error) {
	if methodID == 0 && methodName != "" {
		switch methodName {
		case "New":
			methodID = MethodID_Factory_New
		case "NewTable":
			methodID = MethodID_Factory_NewTable
		}
	}

	reqBuf := ffigo.NewReader(args)
	switch methodID {
	case MethodID_Factory_New:
		var base int64
		{
			tmp := reqBuf.ReadVarint()
			base = int64(tmp)
		}
		r0 := impl.New(base)
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "calc.Calculator")))
		}
		return resBuf.Bytes(), nil
	case MethodID_Factory_NewTable:
		r0 := impl.NewTable()
		resBuf := ffigo.GetBuffer()
		// HostRef<T> crosses the FFI boundary as an opaque handle ID.
		if r0 == nil {
			resBuf.WriteUvarint(0)
		} else {
			resBuf.WriteUvarint(uint64(registry.RegisterTyped(r0, "calc.Table")))
		}
		return resBuf.Bytes(), nil
	default:
		return nil, fmt.Errorf("unknown method ID %d", methodID)
	}
}

var Factory_FFI_Schemas = []struct {
	Name     string
	MethodID uint32
	Sig      *runtime.RuntimeFuncSig
	Doc      string
}{
	{"New", 1, runtime.MustParseRuntimeFuncSigWithModes("function(Int64) HostRef<calc.Calculator>", runtime.FFIParamIn), ""},
	{"NewTable", 2, runtime.MustParseRuntimeFuncSig("function() HostRef<calc.Table>"), ""},
}

type Factory_Bridge struct {
	Impl     *Factory
	Registry *ffigo.HandleRegistry
}

func (b *Factory_Bridge) Call(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return FactoryHostRouter(ctx, b.Impl, b.Registry, req.MethodID, "", req.Args)
}

func (b *Factory_Bridge) Invoke(ctx context.Context, req *ffigo.FFICallRequest) (ffigo.FFIReturn, error) {
	if req == nil {
		return nil, fmt.Errorf("ffigen: missing FFI request")
	}
	return FactoryHostRouter(ctx, b.Impl, b.Registry, 0, req.Method, req.Args)
}

func (b *Factory_Bridge) DestroyHandle(handle uint32) error {
	if b.Registry != nil {
		b.Registry.Remove(handle)
	}
	return nil
}

func SurfaceFactory(impl *Factory) *surface.Bundle {
	schema := runtime.NewFFISurfaceSchema()
	return surface.New(schema, func(ctx runtime.FFIBindContext) (*runtime.BoundFFISurface, error) {
		bridge := &Factory_Bridge{Impl: impl, Registry: ctx.Registry}
		bound := runtime.NewBoundFFISurface(schema)
		bound.Routes["calc.New"] = runtime.FFIRoute{Name: "calc.New", Bridge: bridge, MethodID: Factory_FFI_Schemas[0].MethodID, FuncSig: Factory_FFI_Schemas[0].Sig, Doc: Factory_FFI_Schemas[0].Doc}
		bound.Routes["calc.NewTable"] = runtime.FFIRoute{Name: "calc.NewTable", Bridge: bridge, MethodID: Factory_FFI_Schemas[1].MethodID, FuncSig: Factory_FFI_Schemas[1].Sig, Doc: Factory_FFI_Schemas[1].Doc}
		return bound, nil
	})
}
